### ISSUE TITLE
White boxes

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#108]
Ikemen Go has white hitboxes Mugen doesn't have. These hitboxes push against each other when they collide causing some troubles with targetbind states.
https://streamable.com/g7d98

Without targetbind. 
https://streamable.com/ir0py

You can see in the second video that Krizalid goes backward slowly until both white hitboxes
arent touching each other.

This doesn't happen on Mugen. FYI there is not any corner.push.veloff lines in the code of this movement.

**Comment by Orochikyocr** [comment]
Ikemen Go has white hitboxes Mugen doesn't have. These hitboxes push against each other when they collide causing some troubles with targetbind states.
https://streamable.com/g7d98

Without targetbind. 
https://streamable.com/ir0py

You can see in the second video that Krizalid goes backward slowly until both white hitboxes
arent touching each other.

This doesn't happen on Mugen.

**Comment by Windblade-GR01** [comment]
These white boxes are the mugen push boxes.
In other words `ground.back` `ground.front` and `height`.
