### ISSUE TITLE
Some characters can't quick-jump after crouching

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen-GO#116]
Noticed that in the case of Ikaruga's K' that he doesn't quick jump when I press down to crouch then jump , neither forward or backward.

This is the command

```
[Command]
name = "jump"
command = D, $U
time = 12
```

Edit: just noticed you have to hold the Up key for longer than usual where it's supposed to be a tap in Mugen & it's closer to how the jumping works or should work according to the command above.

**Comment by SibilantScream** [comment]
The culprit seems to be "command = D".
Adding ~ before D makes it crouch-jumping work but this is not exactly a solution since it voids control fidelity.

**Comment by SibilantScream** [comment]
Related to input bugs it seeems that pressing down then forward quick in any menu repeats the down command twice, I'm pretty sure this prevents many moves to register as they normally would in Mugen. One of the moves that are nearly impossible to register is this:

[Command]
name = "mtackle_x"
command = ~B,DB,$D,F,x
time = 30

**Comment by Orochikyocr** [comment]
Check your keyboards, because maybe this is more a GFWL thing than the input parser itself.

**Comment by Orochikyocr** [comment]
I want to extend this issue with some examples.
I am using a full game that doesn't count with a buffer system. the game uses commands from the command file straight, no helpers, no vars, no maps, or whatsoever.
Using Long jump command.

[Command]
name = "longjump"
command = ~D, $U
time = 11

Long jump command activates a var(5) that is used to determine X speed and afterimage. If longjump isn't detected there is no afterimage.
With  ~D, $U
https://streamable.com/vhs95d

With D, $U without ~
https://streamable.com/8ag9t9

Without using the ~ I have to tap and release down WAY faster to activate longjump command.
I think that is the reason almost all chars have a "~" at the start of the command.

**Comment by Orochikyocr** [comment]
Also tested command = ~B,DB,$D,F,
https://streamable.com/tvzcf2

Used the command in Ryo's fireball

[Command]
name = "koohken1"
command = ~B,DB,$D,F, a
time = 20

I tried first 236 to show I am not deceiving anyone, then I tried 4126 and 41236 and fireball is going out just fine.

**Comment by Orochikyocr** [comment]
https://github.com/Windblade-GR01/Ikemen-GO/issues/368
This should be closed since Gacel is aware and working on the input issues.
