### ISSUE TITLE
Benched characters\Dedicated Striker in Tag Mode to be called in with customisable Statedefs

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen-GO#118]
If it were possible to make it so a player can re-arrange the benched characters with a key & time-out their current character with another key so that they can decide which character to call-in as a striker or as a fighter,

Another case is KoF 2000 Striker system where each player picks 4 characters initially then pass into another round to pick the first 3 as fighters whereas their last character pick is to be benched the whole match as a dedicated striker to be called in using y+a (high punch+low kick).

In the latter example the striker can't be called when the current fighter is in being hit or is performing a super special so I think there could be a customisable way to restrict when they can be called.

The customisable statedef in which the strikers are called should have a way to refer to the caller just incase the caller is knocked & the striker should take their place as a fighter.

Providing more keys for gnarularity would be a boon.

**Comment by Windblade-GR01** [comment]
Ikemen GO already uses 10 keys (Counting the pause button and not counting the arrow keys)
A Xbox controller has 10 keys if you do not count the sticks.
So the only available keys on a controllers are R3 and L3.

We are already full on the key department.

**Comment by SibilantScream** [comment]
Yes I agree that we need some way to cycle teammate order. I suggested more keys just for that, I don't think sticking to the number of buttons a joystick would have is more pragmatic than giving expandable keys config for the user.

I fiddled with tag.ssz & could get to making teammates strike, taunt, & then leave without conflicting with normal tag switch, only problem is I don't know how to make a variable to store the limited number of strikes that's shared among all team members. Arcade version of KoF 2000 had configurable number for strikes.

**Comment by SibilantScream** [comment]
Also just noticed that teammates that come to strike can't hit with their own hitdefs, but the helpers they spawn do, this makes it even more convoluted.

**Comment by Windblade-GR01** [comment]
That's because they are tagged-out. (Via `tagOut`)
You need to use `TagIn` to enable the hitboxes again.

**Comment by SibilantScream** [comment]
Yes that worked, thanks heaps.

**Comment by SibilantScream** [comment]
Something else came up related to TagIn.
When I use it on a teammate he can receive commands from the current fighter, this is a problem because even if this teammate is called to strike & leave & has ctrl = 0 he can still receive a command & interrupt execution.

Do I have access to TagIn or is it presently hardcoded?
