### ISSUE TITLE
Input Control (Ignore & Manual Feed)

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen-GO#119]
If there were a way to completely control input for the character by having the option to squelch certain\all commands & simulate input feed with buffer\hold-down-period control.

Related:
https://github.com/Windblade-GR01/Ikemen_GO/issues/90

**Comment by Windblade-GR01** [comment]
Currently it's not a way to do it.

**Comment by Windblade-GR01** [comment]
So thanks to the new SCTRLs and Assertspecials this is now posible.
Closing this.
