### ISSUE TITLE
[Feature] Being able to have small portraits use players palette

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen-GO#124]
In mugen 1.1, the ability to have it where your small portrait changed it's palette with the characters current palette was removed from mugen 1.0. I think it would be neat if there was a way to support that functionality again and have be switchable from the first palette always to the current palette

**Comment by K4thos** [comment]
are you sure this is the case in ikemen go? All characters I've tested shares palette with lifebar portrait. Not an issue, imo.

**Comment by K4thos** [comment]
turned out the problem was with remappal and the shin gouki character used winmugen palette system, so I didn't notice the problem initially. This missing mugen 1.0 feature will work correctly in 0.96 release.
