### ISSUE TITLE
[Win7_x64] Fail to Load Multiple Times

### ISSUE THREAD

**Issue by SibilantScream** [Windblade-GR01/Ikemen-GO#126]
Booting up lasts for couple of seconds at the loading screen untill it terminates the program.
This happens inconsistently upto ~10 times in a row untill it successfully loads.

Tried removing config files to no avail.

**Comment by SibilantScream** [comment]
It seems like Clark Steel by Alpha Dreams & Misamu K Young was behind this, the .sff specifically. Removing that file made Ikemen load up normally. Unsure why yet, the .sff barely contains ~1300 sprites & there are characters in the roster with .sff containing more than 1300 sprites.

**Comment by Windblade-GR01** [comment]
If you recompile the SFF in fighter factory does it load normally or it still crashes?

**Comment by SibilantScream** [comment]
Resaved .sff in Fighter Factory 3 for Mugen 1.1 & ikemen still crashing at startup.

The sprites arrangement does seem suspicious, highly WIP with hitbox reticules for some sprites not filtered out so it could be an outdated .sff compiler was used.

It still crashes when I remove the faulty character but way less frequently.

**Comment by K4thos** [comment]
this has been resolved in 0.96 (by changing portrait preload code)
