### ISSUE TITLE
[Linux/Manjaro] Can't compile or get some dependencies

### ISSUE THREAD

**Issue by madmaruo** [Windblade-GR01/Ikemen-GO#134]
Hello, I'm trying to compile on Linux, but I get the following errors while the scripts "get.sh" or "build.sh" are running. It does work fine under Docker, aside from the known errors when trying to compile the Mac binaries.

get.sh
> https://pastebin.com/w3HF6agC

build.sh
> https://pastebin.com/zaHp3aAK

**Comment by Windblade-GR01** [comment]
What version of openAL have you been using?

**Comment by madmaruo** [comment]
> What version of openAL have you been using?

The latest one available in the repos, which if I remember correctly, is 1.20.1. 1.19.1 is the one recommended, but I can't get that to install.

I believe this dependency issue is also the same with my other issue report (#135), as Brew also installs the latest version.

**Comment by Windblade-GR01** [comment]
This is the horrible part of having globally installed dependencies.
What package contains the openAL dependencies in Manjaro?

**Comment by madmaruo** [comment]
The package that contains all the dependencies is just called _openal_, according to the instructions from #51. Fortunately got it to downgrade using this command, should work on Manjaro or any other Arch-based distro:

`sudo pacman -U https://archive.archlinux.org/packages/o/openal/openal-1.19.1-2-x86_64.pkg.tar.xz`

No longer having issues when getting dependencies, and I only get an error while building (can't run _cp -r ./script/ ./bin/script/_ because the ./script/ directory was not found), same error I get on Mac (even though that one has openal v1.20.1)

Unfortunately, just like with my Mac VM, the compiled binary drops a bunch of errors: https://pastebin.com/uedF1Hu6

**Comment by RQWorldblender** [comment]
I also have been trying to compile on Ubuntu 18.04, using the PPA https://launchpad.net/~longsleep/+archive/ubuntu/golang-backports to get Go 1.14. I was able to successfully compile IKEMEN Go, but I end up with similar errors that @madmaruo encountered, but also:
`
external/script/main.lua:253: attempt to index a non-table object(nil) with key 'read'
stack traceback:
	external/script/main.lua:253: in main chunk
	[G]: ?
`

**Comment by cyliamargatroid** [comment]
Great point! I'll endorse it! @madmaruo
I've also compiled it on ArcoLinux Plasma 5, I will be updating it.

**Comment by formula1** [comment]
I'm also running into the same issue

```
user@system76-pc:~/Games/Ikemen_GO/build$ bash ./build_cmpt.sh 
cp: cannot stat './script/': No such file or directory
```

**Comment by Windblade-GR01** [comment]
Fixed. Both the build script and the `script` folder problem.
