### ISSUE TITLE
[macOS/Mojave] No output while building, game crashes on startup

### ISSUE THREAD

**Issue by madmaruo** [Windblade-GR01/Ikemen-GO#135]
Since Mac builds are currently not a thing, I tried compiling from source on a macOS KVM. Unlike with my previous issue report (#134), no [apparent] errors show up while getting the dependencies, only getting an error (.bin/script does not exist) when building. I ignored it, as the final result (Ikemen_GO_mac binary) was still being created.

However, whenever I try launching it with the default screenpack, it throws the following errors. (Should be noted that, while this is on a VM, chances are this might be the case when building on real Apple hardware too)

`Gios-iMac:Ikemen_GO_Linux gio$ ./Ikemen_GO_mac
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: NSGL: Failed to find a suitable pixel format
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: NSGL: Failed to find a suitable pixel format

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0xc0002597c8, 0x2, 0x2, 0x0, 0x0)
	/Users/gio/Ikemen_GO/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e/error.go:178 +0x201
github.com/go-gl/glfw/v3.3/glfw.CreateWindow(0x280, 0x1e0, 0xc000219352, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/gio/Ikemen_GO/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200420212212-258d9bec320e/window.go:350 +0x1aa
main.(*System).init(0x48ba500, 0x1e000000280, 0xc000200170)
	/Users/gio/Ikemen_GO/src/system.go:372 +0xd59
main.main()
	/Users/gio/Ikemen_GO/src/main.go:448 +0x1686`

**Comment by averagehat** [comment]
Has there been any progress on this, or is there an older version which works for mac?

**Comment by Windblade-GR01** [comment]
This is already fixed.
The MacOS builds can be get at:
https://ci.appveyor.com/project/Windblade-GR01/ikemen-go

**Comment by averagehat** [comment]
My mistake. I was getting a different error (pasted below just for others) by trying to double-click-execute the Ikemen_GO_mac file directly. (the .command file gives a different error). The application will attempt to start if I run Ikemen_GO_mac from the terminal, but then I get the error documented in #153 https://github.com/Windblade-GR01/Ikemen-GO/issues/153

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x41e2db3]

goroutine 1 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.(*Window).SetIcon(0xc0001ca480, 0xc0002dd620, 0x1, 0x1)
	/code/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:416 +0xe3
main.(*System).init(0x494c860, 0x1e000000280, 0xc0000a0138)
	/code/src/system.go:515 +0x625
main.main()
	/code/src/main.go:480 +0x191c
logout
Saving session...completed.
Deleting expired sessions...28 completed.

```
