### ISSUE TITLE
Chars floating away

### ISSUE THREAD

**Issue by Spynathan** [Windblade-GR01/Ikemen-GO#141]
Some moves will cause chars to just float away, I've so far noticed it with several of card sega wars chars and I also noticed it with a batman char. Since it's a bit tricky to replicate with some of the CSW chars, I'll link you the batman as it's very easy to replicate. The A combo will end off with batman swinging on a rope to kick the enemy into the air, this will cause the enemy to continue floating into the unknown heavens and beyond. Here's a link to the batman, for testing. http://www.mediafire.com/file/nnvawoa75yx3i6d/Batman.zip/file

**Comment by K4thos** [comment]
"fixed". The problem was with character's state 98397917317 being outside int32 range. In such case mugen truncates the number to 2147483647 while ikemen go didn't have such precaution in function that converts string into int.
