### ISSUE TITLE
Pokemon-specific Attack system

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen-GO#145]
Idea (For Fangame Purpose only):

0 = None
1 = Normal
2 = Fighting
3 = Flying
4 = Poison
5 = Ground
6 = Rock
7 = Bug
8 = Ghost
9 = Steel
10 = Fire
11 = Water
12 = Grass
13 = Electric
14 = Psychic
15 = Ice
16 = Dragon
17 = Dark
18 = Fairy

Data Codes example for Gardevoir being Psychic/Fairy
```
[Data]
resistence = 2,2,14; When Doubled mean Double Resistences.
weakness = 4,8,9
immuned = 16; When hit by Dragon attacks, you won't be able to Flinch or take damage at all.
```
Hitdef/Projectile codes when a Certain Pokemon uses Moonblast
```
[state 000]
type = hitdef
attacktype = 17
```
and for Type changes.
```
[state ChangeType]
type = changetype
trigger1 = !time
; Whenever if someone wants to changes types
; For example: Fighting Type
resistence = 6,7
weakness = 3,14
immuned = 0; When Zero, You're not immuned to anything.

**Comment by Orochikyocr** [comment]
You can literally do this with MAP...
https://github.com/K4thos/Ikemen_GO/wiki#mapset
Check the wiki.
