### ISSUE TITLE
Two issues to be looked on. 

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#156]
The first one was already reported on Discord, but I would like this post to be left here until someone shows interest in fixing it.
https://streamable.com/49b6zx
Targetstate and hitdef p2stateno are totally ignored if the char that uses any of these parameters is a partner in simul or tag(It doesn't happen if the char is the first player of the team) This happens on Mugen too, still, I don't think is wise to ignore it.  
The second issue is that attachedchar isn't being loaded after the first round in Turns mode.

Ill dropped tag support on my project because the first bug and the second one is really affecting the development of the same because my lifebars are using attachedchar to work. 

Thanks in advance.

**Comment by thoj900** [comment]
for the custom state issue, dont use changestates in the custom state especially if it uses (p2 stateno=) as triggers, changeanim2 will still work, and put your targetstate and target bind in the same state of the character initiating the move. i ran into the same problem, but this way avoids all of this. youll have to rewrite all the throws, but it shouldnt be hard. All my characters now work regardless of simul or tag, or being p1 or p2.

**Comment by Orochikyocr** [comment]
> changeanim2 will still work, and put your targetstate and target bind in the same state of the character initiating the move. i ran into the same problem, but this way avoids all of this. youll have to rewrite all the throws, but it shouldnt be hard. All my characters now work regardless of simul or tag, or being p1 or p2.
> 
> Heres an example of the above method working with the same character 3 times on 1 team:
> https://streamable.com/e3l8yr

Changeanim2 is inside the targetstate so it is never reached. For the coding POW IMO is better to have the targetstate as you said, inside the same state, but in my case this doesn't work, I had to put the targetstate in a negative state(state -3), which IMO is not an elegant way by any means to solve this. I already know how to "solve" it, but this is clearly a bug and it has been there since Mugen with no means of solving it, now since IKGO is open source I hope someone someday take some time to fix something that is not technically broken, because the code works perfectly for the first player of the team, on single, and turns.
![image](https://user-images.githubusercontent.com/42851314/88453643-0f5c2e80-ce26-11ea-8b06-a4d026bd7eec.png)

**Comment by Orochikyocr** [comment]
I was informed thru Discord that attachedchar not loading on turns has been fixed. Thanks.
