### ISSUE TITLE
[Feature] bgmusic.life on every round, Stage BG audio volume manipulation, and Survival mode like mugen

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen-GO#158]
While bgmusic.life is a great feature , the one issue I've had with it is that it only plays on the final round of a set. I nice option to have would be to have the option to have it play on every round similar to how street fighter II, Fighters History Dynamite/Karnov's Revenge, etc does it 
https://youtu.be/pyn2FL1fMWo?t=11

Another feature that would be great to have is the ability to change the volume of the stage so you can create a fadeout effect for the music, yet again similar to street fighter II, Fighters History Dynamite/Karnov's Revenge, etc

Similar to bgmusic.life, I feel like there should be the option to have survival mode operate similar to how mugen does it with an endless match of characters each time on win rather than a single round facing infinite opponents for each round. Since with mugen's survival you did not know who you where going to face up against unlike in ikemen GO Plus where it tells you each time with a win.

**Comment by K4thos** [comment]
bgmusic.life can already work on every round, read the documentation: https://github.com/K4thos/Ikemen_GO/wiki#stage_music_bgmusiclife

I don't understand third paragraph of your post at all. Survival mode already operates in similar fashion to mugen but offers additional functionality at the same time (a way to create finite survival modes, changing stages, using select.def character parameters for each opponent, order parameter dedicated just to survival mode). And at the same time, from player's perspective it behaves the same as mugen by default (infinite random opponents with limited life recovery between fights). Doing it exactly like mugen would be a downgrade, not an improvement. This idea is definitely not an enhancement (unless I miss something).
