### ISSUE TITLE
[Feature] Assert Special SCTRL to make opponent not auto-turn or auto-face you

### ISSUE THREAD

**Issue by thoj900** [Windblade-GR01/Ikemen-GO#163]
Repost from K4thos git:

This is usually a problem on add004 or tag system, where if a cross up happens (call an assist and the assist is behind the enemy and you are in front), the enemy will try to auto face the assisting partner. This usually doesnt happen in tag fighting games, and it kind of messes up some dynamic.

I've asked this on forums, and tried looking at new state controllers in ikemen specifically, I don't think there is a sure fire way of doing this (spawning helpers etc). without some kind of fallback. Which is why I suggest maybe an sctrl that will treat you as some kind of non-player/non-helper so the enemy doesnt autoface you? Sorry if this already exists, maybe I missed it.

**Comment by K4thos** [comment]
v0.96 will have new AssertSpecial called noturntarget: while asserted, keeps the opponent from automatically turning to face the character. This should be enough to handle situations like this, right?

btw. no need to repost requests and issues in 3 different places (especially MFG where we can't close fixed/implemented tickets). Gacel's github is most busy and organized when it comes to bug reporting these days, so posting it here is enough.

**Comment by thoj900** [comment]
Thanks for the response! sorry will keep in mind

**Comment by thoj900** [comment]
Sorry one more thing, just to make sure, if asserted it will keep the opponent from automatically facing whoever is using the trigger, but STILL automatically face ones who don't have the assert correct? Like how helper (normal non-player types) don't make an enemy turn towards them, but enemy will still turn towards the main player?

**Comment by K4thos** [comment]
it makes the opponent only ignore the character that has it asserted (as mentioned in first post). I don't know how else to desribe it.
