### ISSUE TITLE
Spirits mechanics and Spirit battles like what Smash Ultimate has

### ISSUE THREAD

**Issue by JTDaddy17** [Windblade-GR01/Ikemen-GO#165]
How about a feature to add Spirits into Ikemen? In Smash Ultimate, Spirits are characters that you can equip and you can level them up while in turn, the Spirit character provides your fighter with enhanced abilities, like added attack power, defense, speed, etc. and can even take advantages to certain attacks and Spirit types they're strong against. e.g. Grab type Spirits enhances your grab attacks and are strong against Defense Spirit types and weak against Attack Spirits types, Defense Spirits are strong against Attack Spirits but weak to Grab Spirits, Attack Spirits are strong against Grab Spirits but weak to Defense Spirits. This video basically explains how this mechanic works: [](https://youtu.be/JhGtuG12ZrM)

I wonder if Ikemen can have a feature like this or something similar of the sorts, I think this would be a neat addition!

**Comment by Windblade-GR01** [comment]
This is too game specific to add.

We are planning to add "style" select feature.
The feature could also be used for things like spirits.

**Comment by JTDaddy17** [comment]
Ah, yeah I think we talked about that in the Ikemen Discord server not too long ago lol
