### ISSUE TITLE
Rounds & Victory Sounds Don't End When Screen Closes

### ISSUE THREAD

**Issue by Retroid84** [Windblade-GR01/Ikemen-GO#169]
Hi, i have long round audio that lasts through a whole round for about 90 seconds. It is for my aannouncer who will say various lines during the match. However whern a match is finished or i exit back to the main menu the sound file does not end so i will have my announcer speaking whilst i am back on the main menu or when i am on round 2, round 1's sounds still play etc. On MUGEN when you finish the round or exit back to the main menu the audio clips end but on your Ikemen it continues until it reaches it's max duration.

Also the victory screen song i use does the same, when i loe a match it goes to the victory screen and plays the music etc but then goes straight to the continue screen and the victory music continues to play! These issues didn't happen in Mugen and would mean downgrading my screenpack quality if i have to remove or shorten these clips etc.

Will this be something you can fix? All that needs to be done is to make the round sounds end when the match is exited or finished and same for the victory screen, once you go past that screen the music needs ot be stopped.

Much apprecaited and thanks very much in advance!

Retroid84

**Comment by Retroid84** [comment]
To clarify i have 90 seccond audio clips from Rounds 1 - 9 and during the round the announcer will say various things. Once the round is over form a loss or win, round 1's audio would end when round 2 came on etc but it isn't in Ikemen, if i finish the round early and get onto Round 2 then whatever is left of round 1's audio clip will continue to play during round 2. Then the same for round 3 onwards. Same for the victory screen music. When the victory screen closes and goes onto the continue screen the music does not stop and continues to play over the continue screen, thanks.

**Comment by K4thos** [comment]
this is fixed locally, won't be a problem in next major build

**Comment by K4thos** [comment]
> When the victory screen closes and goes onto the continue screen the music does not stop and continues to play over the continue screen, thanks.
this one is working as intended and I don't see a point of changing it. It allows stage music to continue playing if there is no unique victory screen or continue screen music: https://youtu.be/-FbLoW2MEqI
And you can assign track to both continue screen and victory screen separately. If for some reason you want dead silence during continiue screen just assign some dummy track as continue screen music in system.def.

**Comment by Retroid84** [comment]
That is amazing!!! Can't thank you enough ha =)
I shall eagerly await the next release then. Also thank you for the advice on the continue screen music, i wasn't aware Ikemen could allow music on the continue screen which i definitely prefer over silence. Realised i can set it under the Music section in the System.def so that is resolved now thanks a lot. 
I am too used to Mugen and all it's limitations ha, I have a couple of other small questions too so will open requests for them.
Loving this Ikemen so far though, keep up the great work and cheers again!
