### ISSUE TITLE
Stage Pre-Loading, Can It Be Configured?

### ISSUE THREAD

**Issue by Retroid84** [Windblade-GR01/Ikemen-GO#174]
Hi again, I don't know if this would even come under being a bug and probably a requirement of Ikemen so doubt it can be changed but thought i would ask anyway.

Basially i now have to resize all my stages from Mugen to Ikemen to make them fit as they are all off center etc. I do not mind this at all as i was going to change them all anyway.

However in Mugen the stages load once the game starts meaning i can alt + tab out of Mugen, make a change to the stage and reselect it after the character select screen and the stage will now show it's changes. However i have noticed in Ikemen this does not work and to see any changes in game i have to close and restart Ikemen which is very time consuming when editing over 100 stages.

I can live with it if it has to stay like this though as Ikemen is worth putitng the time and effort into but thought i would check with you first before i make a start. Preferably it would be best if i can turn pre loading of stages on or off somehow, is this possible?

Many Thanks Again! Much Appreciated

**Comment by K4thos** [comment]
don't see much point in changing current behaviour when you can quickly reload stage via `-s` command line parameter. Like this:
`Ikemen_GO.exe kfm kfm -s stages/stage0.def`
create a batch file: https://www.windowscentral.com/how-create-and-run-batch-file-windows-10
or shortcut with parameters: https://www.digitalcitizen.life/shortcut-arguments-parameters-windows
and you will be able to reload stage faster compared to exiting, reselecting characters and stage.

Unless there is some advantage in what you're suggesting that I'm missing I think the issue can be closed.

**Comment by Retroid84** [comment]
That is absolutely fine i shall create batches, I would have happily spent
months doing my stages the long way round anyway as your Ikemen is sooo
much better than Mugen ha.

Thanks a ton again for all your help it has been greatly appreciated and i
shall leave you alone now ha.

Cheers

**Comment by K4thos** [comment]
just tested, stage is completely reloaded upon pressing shift+f4, so changes can be tested on the fly like in mugen. This was not the case when this ticket was opened iirc.
