### ISSUE TITLE
Player Select on Versus Screen Buggy After Going Past P2

### ISSUE THREAD

**Issue by Retroid84** [Windblade-GR01/Ikemen-GO#175]
Hi, on the versus screen when you have selected Tag or Turns mode. How you can press left or right to select which character you want to start the match playing as. Well you can press left and right to select the first two of the selected characters which works fine but to select the third or above it seems buggy. Pressing left and right or up or down doesn't work at first, the only way to select the third character seems to be to randomly mash the up down left and right keys and sometimes it will select it and sometimes not. Just wondering if this can be fixed so presing either up and down or left and right keys will easily select any of the characters to start the match with. Like i said the first two i can press left and right to go back and forth between on the versus screen with ease and works fine but always seems like a task to select the third or above characters and sometimes can't select it before the time the versus screen displays for ends.

Thanks a million in advance mate!

**Comment by K4thos** [comment]
this is more of a question "how to", not a bug report or feature request. Github issues page is not a place for general questions how to use the engine. Consider joining discord instead: https://discord.gg/XNbRqHM

As for the question. it does work as intended as far as I know - left and right changes the current character that you want to change position, up and down moves that character position in team.

**Comment by Retroid84** [comment]
Oh sorry about that I shall use the discord in future. I have figured it out now you press up and down to select which character and use left and right to move it up and down the name list. 

However in relation to feature requests and this post, would it be possible to add a cursor in the future or allow blinking text for the name you are currently on? As mistakes can still be made when selecting due to not always knowing which name you currenlty have as the active one. 

Thanks Again Mate

**Comment by K4thos** [comment]
no need to add it since this feature is already there, just not enabled by default (none of the screenpack features are documented, so it's normal that you're not aware of them of course). Add following parameters to system.def under [Select Info]:
```ini
p1.name.active.font
p1.name.active.font.scale
p2.name.active.font
p2.name.active.font.scale
```
The ticked can be closed, imo, considering there is no bug nor feature request left here.

**Comment by K4thos** [comment]
When I now think about up/down changing position while left/right active character only makes sense when portraits are placed in horizontal line. When there is only 1 portrait but multiple lines in a vertical line (which is usually the case in mugen screenpacks that don't take advantage of ikemen go features) having those buttons functionality reversed would be more intuitive. I will make buttons functionality during vs screen adjustable via screenpack parameters in the next major build.

**Comment by Retroid84** [comment]
Wow, that is amazing thanks so much! You have been incredibly helpful for
me today I couldn't be happier ha.

Thanks Again & Have A Great Day!

**Comment by K4thos** [comment]
Initial report and further discussion are no longer relevant since this commit: https://github.com/K4thos/Ikemen_GO/commit/ef5cda387755770d10b548bb5a9ff4da51f9d743
