### ISSUE TITLE
[Feature] Multi layer animations for lifebars

### ISSUE THREAD

**Issue by Rurouni-X** [Windblade-GR01/Ikemen-GO#178]
This is one of the things that are really missing in creating lifebars. While for older lifebars it doesn't make much difference, converting newer lifebars using multiple layers would be a great addition.
Let's take "KO" as an example. We currently have something like this:

Code:

    ; KO
    KO.time    = 0               ;Time to show KO component
    KO.offset  = 320,240    ;Component for KO display
    KO.anim    = 100            
    KO.snd     = 2,0             ;Sound to play for KO announcement
    KO.sndtime = 0

You can use only one layer. If you want to use 2 layers or more, you have to put all the sprites together, taking more work and making the sff heavier. It is not the best way but it works to some degree. Multiple layers would make this more functional because certain animations only use fade and movement on the x and/or y axis. So it would be great to have something like this:

Code:

    ; KO
    KO.time    = 0              ;Time to show KO component
    KO.offset  = 320,240         ;Component for KO display
    KO.bg0.anim    = 100            
    KO.bg1.anim    = 101            
    KO.bg2.anim    = 102            
    KO.snd     = 2,0             ;Sound to play for KO announcement
    KO.sndtime = 0

Each "bg" having its respective properties: scale, layer, offset. A maximum of 5 layers is more than enough.
In MUGEN, the maximum bg for [Lifebar] and its variations are only 3: bg0, bg1 and bg2. Except for [Time], you can only use a "bg.spr" or "bg.anim". For better compatibility, bg0 = bg as it is already in MUGEN.

And taking advantage of the moment, I would like to suggest that [Time] could use different animations/sprites if the time was defined as infinite. Example:

Code:

    [Time]
    pos = 322,12
    bg0.anim = 200 
    bg1.anim = 201
     
    bg0.inf.anim = 300 
    bg1.inf.anim = 301 
     
    ; Time count display
    counter.offset = 0,52
    counter.font = 2,0, 0
    counter.scale = 2,2
    ; Ticks for each count
    framespercount = 60

**Comment by two4teezee** [comment]
This would be a good, probably superior, alternative to what I proposed (issue 209).

**Comment by K4thos** [comment]
this feature was recently implemented by two4teezee

**Comment by GAMER981** [comment]
Where to download this feature implemented by two4teezee ?
Thnx !
