### ISSUE TITLE
Request - Combo Counter Sounds Built Into Ikemen

### ISSUE THREAD

**Issue by Retroid84** [Windblade-GR01/Ikemen-GO#180]
Hi, just making a request to see if this can be done and if you have any interest in implementing it at all? Basically it would be great if sound clips could be assigned for the combo counter. Like in Killer Instinct when you reach 10 hits, 20 hits and so on it will play a diferent sound clip. 

I know this can be done in Mugen but requires you to code it etc for each character and that is something i will never have time for. It would be great if this was done in Ikemen itself (through the fight def etc?) so every character you play as will use the same sound clips when reaching a certain number on the combo counter without having to do it in each character's files?

Thanks

**Comment by K4thos** [comment]
this is already supported natively via `data/action.zss` file. Simply add appropariate PlaySnd sctrl code right below LifebarAction lines that calls combo messages.

**Comment by xMetsux** [comment]
Could I possibly have an example of how this code is supposed to look as far as being added below the lifebarAction lines go.
Probably something super simple i'm just still new to Ikemen.  

Thanks
