### ISSUE TITLE
Error from guthub... (build process)

### ISSUE THREAD

**Issue by CTRL-ALT-DEL-80** [Windblade-GR01/Ikemen-GO#181]
Building Ikemen GO...

# github.com/go-gl/gl/v2.1/gl
exec: "gcc": executable file not found in %PATH%
# github.com/go-gl/glfw/v3.3/glfw
exec: "gcc": executable file not found in %PATH%
# github.com/timshannon/go-openal/openal
exec: "gcc": executable file not found in %PATH%

Just got this error, how to solve that please?

**Comment by Windblade-GR01** [comment]
You do not gave "gcc" in path.
Did you follow the build guide?

**Comment by CTRL-ALT-DEL-80** [comment]
Yes, all the step... installed all the app needed and also add system variable, but got this error...

Finally i have downloaded a builded one when i found it, you can close issue...

Thank
