### ISSUE TITLE
[Feature] "Missing" standard animations & sounds for lifebars

### ISSUE THREAD

**Issue by Rurouni-X** [Windblade-GR01/Ikemen-GO#182]
One of the things that is standard in official fighting games that is missing from MUGEN, and so far (?) in IKEMEN, is the "perfect win" animation/text. You can add them in the chars themselves, but having that in the lifebar itself would simplify the work and make a great addition. Something like this:

Text form
Code:

    ; Perfect
    PFT.time    = 0              ;Time to show "Perfect" component
    PFT.offset = 160, 70
    PFT.font   = 1,5
    PFT.text   = Perfect
    PFT.displaytime = 60
    PFT.snd    = 3,0

Animation form
Code:

    ; Perfect
    PFT.time    = 0              ;Time to show "Perfect" component
    PFT.offset = 160, 70
    PFT.anim   = 300
    PFT.displaytime = 60
    PFT.snd    = 3,0

____________________________________

- Different win text/animations for team 1 and team 2. Something like this:

P1 side:
Single   - win1.a.anim =
2 chars - win1.b.anim =
3 chars - win1.c.anim =
4 chars - win1.d.anim =

P2 side:
Single   - win2.a.anim =
2 chars - win2.b.anim =
3 chars - win2.c.anim =
4 chars - win2.d.anim =

Of course, for each mode (number of chars) the rest of its respective parameters:
Time, offset, font and text or anim/sprite, scale and displaytime.

____________________________________

- "Challenger" and "beat by" text/anim

This function would be displayed for versus mode playing with a friend/online instead of the score. Both players start with the text "challenger" (editable), and the winner begins to have the number of wins displayed with the (editable) text "beat by...". For Arcade mode, playing against a challenger the score would no longer be displayed (but would continue to be counted) and would function as in versus mode, returning to the fights against the CPU the score would be displayed again and the victories would be omitted. An alternative solution would be to have the victory and the score alternate with each other.
  
____________________________________

- Sounds for win/win2/3/4 and draw

MUGEN has always been lacking, some lifebars use a workaround combining the sounds of KO and Winner in the same sound.
For draw game, if it is not coded in the char it is not possible.

**Comment by K4thos** [comment]
> One of the things that is standard in official fighting games that is missing from MUGEN, and so far (?) in IKEMEN, is the "perfect win" animation/text. You can add them in the chars themselves, but having that in the lifebar itself would simplify the work and make a great addition.
already implemented: https://github.com/K4thos/Ikemen_GO/wiki/Lifebar-features#existing_round_wintype

> Different win text/animations for team 1 and team 2
lifebar win text can be customized depending on team size

> "Challenger" and "beat by" text/anim
implemented here: (not 100% as suggested but the way it's done in most modern games)
https://github.com/K4thos/Ikemen_GO/wiki/Lifebar-features#new_wincount

> Sounds for win/win2/3/4 and draw
from what I see in source code all these elements are AnimTextSnd so should support sounds already. There is a also lifebar action sctrl that can be used though action.zss to play lifebar sounds if above is not enough: https://github.com/K4thos/Ikemen_GO/wiki/State-controllers#new_lifebaraction
