### ISSUE TITLE
Built-in Combo Announcer

### ISSUE THREAD

**Issue by cyliamargatroid** [Windblade-GR01/Ikemen-GO#189]
Like MVC or other fighting games, The announcers will say

YES
GOOD
VERY GOOD
FANTASTIC
MARVELOUS

That's my idea though

```
announcer.combo.px.sound = 16,0
announcer.combo.px.anim = 16010

**Comment by K4thos** [comment]
upcoming v0.96 makes this idea redundant. That's what LifebarAction sctrl is for: https://github.com/K4thos/Ikemen_GO/wiki#sctrlnew_lifebaraction
