### ISSUE TITLE
Make a example  project for interactive stages.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen-GO#19]
This could help to showcase the attached char feature.
It could be also used as a example of Variable Map.

**Comment by cyliamargatroid** [comment]
Whenever characters gets hit on the ground and then the ground gets destroyed, Moves down to the next floor.

-- My Idea.

**Comment by Mike77154** [comment]
Hey, You can use the Interactive mugen pack by electro for learning this

**Comment by Windblade-GR01** [comment]
Kamekaze and other users have been releasing interactive stages for a while.
Good enough to show how to implement interactive stages.
