### ISSUE TITLE
A Bug that Ikemen-GO uses too much memory in sffNew() -> loadSff() -> readV2() ->gl.TexImage2D

### ISSUE THREAD

**Issue by xk5320** [Windblade-GR01/Ikemen-GO#192]
@Windblade-GR01 @shinlucho 

Thank you for this great program!! but I found a bug about uses too much memory in sffNew() when gl.TexImage2D use in sys.mainThreadTask <- func()......

When the game's sff files in the chars and stages directory increases to hundreds of thousands, especially when using sff v2, png format spr, every time you start the game, run in motif.lua to 
`motif.files.spr_data = sffNew(motif .files.spr)`

image.go runs to loadSff() -> readV2()  :

			sys.mainThreadTask <- func() {
				gl.Enable(gl.TEXTURE_2D)
				s.Tex = newTexture()
				gl.BindTexture(gl.TEXTURE_2D, uint32(*s.Tex))
				gl.PixelStorei(gl.UNPACK_ALIGNMENT, 1)
				gl.TexImage2D(gl.TEXTURE_2D, 0, gl.RGBA, int32(rect.Max.X-rect.Min.X),
					int32(rect.Max.Y-rect.Min.Y), 0, gl.RGBA, gl.UNSIGNED_BYTE,
					unsafe.Pointer(&rgba.Pix[0]))
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE)
				gl.Disable(gl.TEXTURE_2D)
			}

Every time the gl.TexImage2D statement creates a texture, it will waste some memory in sys.mainThreadTask <- func()
Sometimes the memory waste will be as much as 2G or more！！

Mugen 1.1b memory usage is about 100~200M :-(
![image](https://user-images.githubusercontent.com/41437626/99155051-95f78d00-26ef-11eb-8180-4c9ccfad6ac0.png)

![image](https://user-images.githubusercontent.com/41437626/99155044-88420780-26ef-11eb-90d9-1aa71ce22f1f.png)

If the program statement is temporarily changed to the following：

			//sys.mainThreadTask <- func() {
				gl.Enable(gl.TEXTURE_2D)
				s.Tex = newTexture()
				gl.BindTexture(gl.TEXTURE_2D, uint32(*s.Tex))
				gl.PixelStorei(gl.UNPACK_ALIGNMENT, 1)
				gl.TexImage2D(gl.TEXTURE_2D, 0, gl.RGBA, int32(rect.Max.X-rect.Min.X),
					int32(rect.Max.Y-rect.Min.Y), 0, gl.RGBA, gl.UNSIGNED_BYTE,
					unsafe.Pointer(&rgba.Pix[0]))
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE)
				gl.TexParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE)
				gl.Disable(gl.TEXTURE_2D)
			//}

The memory usage will be below 300M, and no abnormality was found

Of course, I hope you find the best solution to remove this bug!!!!

**Comment by K4thos** [comment]
I've noticed it too recently: https://discordapp.com/channels/233345562261323776/233363722934943744/777240283313078302

170MB file with hundreds of 1280x720 32 bit images eats up... 2.5GB of RAM, so more than 10x than it should. The same problem exists on Ikemen GO Suehiro builds from 2018.01.09, so it's unrelated to any of our changes.

**Comment by xk5320** [comment]
So please @Suehiro , , how to deal with this problem, I think you should be more familiar with him than me...thanks a lot~~

**Comment by xk5320** [comment]
By the way, Discord is no one online :-(

**Comment by Windblade-GR01** [comment]
Fixed in fe29412d0d9dc23bbadd126968f35eba5130f511.
Thanks for the detailed info about it xk5320.
