### ISSUE TITLE
FightFX Scale is not implemented.

### ISSUE THREAD

**Issue by Windblade-GR01** [Windblade-GR01/Ikemen-GO#20]
Iniside the figth.def is a function that is FightFX Scale it looks like this:
```
[FightFx]
scale = 4
```
It's one of the Mugen 1.0 lifebar new features that is not implemented.

**Comment by K4thos** [comment]
https://github.com/K4thos/Ikemen_GO/commit/944739524f7cdedbb1659008fc1cff75d19660e3
Implemented, although I'm still not sure if FightFx scale implementation is accurate. Based on my tests it works with:
- winmugen lifebar (320x240 localcoord, fightfx scale = 1)
- mugen1 lifebar (1280x720 localcoord, fightfx scale = 4)
- Legacy screenpack (1280x720 localcoord, fightfx scale = 0.5)
- King of Fighters WING V. 2020 fullgame (800x480 localcoord, fightfx scale = 2)

But it didn't work correctly for add004 lifebar that uses 320x180 localcoord, fightfx scale = 1. That was the reason why this feature was not implemented for so long.

As a workaround I've added scale adjustment when Y localcoord < 240 by dividing these values and it seems to do the job, although not sure if this is not just coincidence. We will see if there will be any reports regarding this functionality.
