### ISSUE TITLE
Show win counter on each side in VS modes instead of scores!

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#206]
As the title, show the number of matches won by each player instead of the score. Preferable that the counter does not reset on player lose/win, perfectly for "First To" challenges.

**Comment by K4thos** [comment]
done: https://github.com/K4thos/Ikemen_GO/wiki/Lifebar-features#new_wincount

**Comment by Orochikyocr** [comment]
Done is done, thanks K4thos!!
