### ISSUE TITLE
Gouken by Alexlexus freezes engine before match starts

### ISSUE THREAD

**Issue by LasombraDemon** [Windblade-GR01/Ikemen-GO#208]
Not even an error. Just freezing.

https://www.mediafire.com/file/hdbc6m2x7ogmmeq/gouken.7z/file

**Comment by K4thos** [comment]
your link is dead, so can't test it, but I've tried this version of Gouken by Alexlexus: https://mugenarchive.com/forums/downloads.php?do=file&id=83932-gouken-alexlexus
It didn't freeze the game on 0.97.

**Comment by LasombraDemon** [comment]
Tried all the Goukens I have, they all work now! Yay!
