### ISSUE TITLE
Make/Allow a Packaged File Format?

### ISSUE THREAD

**Issue by Kokorz** [Windblade-GR01/Ikemen-GO#210]
Would it be possible to make a files packer that packs everything (SFFs, DEFs, AIRs, CNS/ZSSes, etc, etc) a character/stage/motif/etc has into one file that Ikemen GO would load? It's mainly to make it harder for random people to just rip sprites off a character easily with Fighter Factory. If making it load at once would be annoying, making it extract at temp in appdata could also be a possibility as it's a hidden folder.

In case I sound too confusing, I'm thinking something along the likes of the PAC file format Arc System Works tends to use in BlazBlue for their PC ports.

**Comment by Orochikyocr** [comment]
The same way people ripped sprites from commercial games for Mugen.  You and I are those random people. ;)

**Comment by Kokorz** [comment]
> The same way people ripped sprites from commercial games for Mugen. You and I are those random people. ;)
> In the case you want this to protect your OWN copyright assets there are plenty of commercial solutions to pack and encrypt the content as Cameyo or Enigma.

I'll def look into Enigma. Cameyo requires payment which is something I am not willing to pay for (yet anyway). Thanks for this info, Orochi!

**Comment by Windblade-GR01** [comment]
Enigma Protector also requires payment.
Enigma VirtualBox (the free one) allows you to package the files but offers no encryption.

I know 3 protection solutions Cameyo, Enigma Protector and VMProtect.
While they are not prefect (no security method is) they are very hard to crack and takes a lot of effort to do so.
