### ISSUE TITLE
pX.front<val> is broken for [Guardbar] and [Stunbar]

### ISSUE THREAD

**Issue by two4teezee** [Windblade-GR01/Ikemen-GO#211]
Looks like the pX.front<percentage> functionality in [Stunbar] is broken. The default front element is not displayed, nor are any front elements with percentages lower than the highest pX.front<percentage>. Only the pX.front<max percentage> element is rendered. There is an exception to this, if the pX.front<val> elements point to the same spr/anim then it will display (sometimes); of course, this invalidates the usefulness of this feature.

**Comment by K4thos** [comment]
already fixed in 0.96.1, should be closed

**Comment by two4teezee** [comment]
I'm still seeing issues with [Stunbar]. [Guardbar] seems fully fixed now, but [Stunbar] has some strange behavior to it that I can't seem to work around - I wonder if it's a logic-based thing (bar fills up instead of empties). Of note, for example p1.front80.anim only displays the first frame from the animation, and also in some cases, on first hit, the stun meter bar does not show an increase. I'll keep digging at it.

**Comment by two4teezee** [comment]
I found the issue in lifebar.go and included it in my pull request. We can close this, assuming that my changes will be merged into the next release.
