### ISSUE TITLE
Character named "Random" crashes the engine only after being seen in select screen, not upon loading

### ISSUE THREAD

**Issue by LasombraDemon** [Windblade-GR01/Ikemen-GO#217]
Extremely weird error.

![imagen](https://user-images.githubusercontent.com/74574875/105252232-d6dea880-5b5b-11eb-9126-8d0e0e56c080.png)

https://www.mediafire.com/file/ijsexkk6u2iofqx/ran2om.7z/file

**Comment by Windblade-GR01** [comment]
Oh...
Maybe I know why this is happening.

**Comment by K4thos** [comment]
fixed
