### ISSUE TITLE
Mugen Games can be loaded by Ikemen ?

### ISSUE THREAD

**Issue by liberodark** [Windblade-GR01/Ikemen-GO#220]
Hi,

Im try to understand if Ikemen-GO have possibility to run : 
"Teenage Mutant Ninja Turtles  Tournament Fighters X" for example.
My idea is try to run mugen game natively on linux.

Best Regards

**Comment by Orochikyocr** [comment]
Ikemen Go runs on Linux natively.
Ikemen GO does not run Mugen, Ikemen Go is compatible with Mugen content, chars, stages and screen packs.
IKemen Go is not an engine that runs other engines. It interprets Mugen content previously mentioned with its own code, nothing related to Mugen.
No point in running a closed source engine "natively", it is like running MS Office on Linux when we have Libre Office.
Threat Ikemen as you do on Mugen, copy chars and stages to their respective folders and modify select.def and you are ready to play Mugen content in Windows, Linux and Mac.

**Comment by Windblade-GR01** [comment]
> Threat Ikemen as you do on Mugen, copy chars and stages to their respective folders and modify select.def and you are ready to play Mugen content in Windows, Linux and Mac.

You can also copy the Ikemen GO `binaries_only` zip release over a copy of a MUGEN game.
Ikemen GO does not need the `Microsoft.VC90.CRT`, `plugins` or  `Elecbyte.MUGEN.libs` folders.
