### ISSUE TITLE
textwrap problem

### ISSUE THREAD

**Issue by evildarklxs** [Windblade-GR01/Ikemen-GO#226]
winquote.offset = 659,71;661,0
;winquote.spacing = 0, 0
winquote.font = 2,0,1
winquote.window = 0,0, -21,720
winquote.delay = 0
**winquote.textwrap = w**  

**before it allows to place letters vertically, now it is by word**

I need to change this for a project Ive

**Comment by K4thos** [comment]
not enough information to reproduce. Upload screenpack with victory screen already configured the way you want it to be displayed, that showcases the issue. Problems like this always needs to be tested on both mugen and ikemen and pasting your values won't work on default screenpack.

**Comment by evildarklxs** [comment]
> not enough information to reproduce. Upload screenpack with victory screen already configured the way you want it to be displayed, that showcases the issue. Problems like this always needs to be tested on both mugen and ikemen and pasting your values won't work on default screenpack (due to different localcoord and fonts).

**it is a problem with the winquote.window function, don't respect the coordinates**

here an example with the same parameters (winquote.window = 18,171, 51,228)

images mugen :
![mugen000](https://user-images.githubusercontent.com/78336781/121088252-70c58b80-c7b3-11eb-94e7-6e2d43f7836a.png)

images ikemen:
![ikemen001](https://user-images.githubusercontent.com/78336781/121088248-6f945e80-c7b3-11eb-82a2-41a29b413cdd.png)

**Comment by K4thos** [comment]
done
