### ISSUE TITLE
M.U.G.E.N-like legacy character select

### ISSUE THREAD

**Issue by ghost** [Windblade-GR01/Ikemen-GO#229]
I was annoyed when it came to the "looping" character select (e.g. kfm, randomselect, kfm, randomselect, etc.) and two players share the same roster.

Why not give an enhancement of giving the option to use the legacy character select back when M.U.G.E.N was popular.

**Comment by Windblade-GR01** [comment]
It has been like Mugen since years already.
The version you are using must be very very outdated.
