### ISSUE TITLE
A minimalist approach to the engine.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#232]
In the Ikemen Discord people do not stop suggesting to add stuff that is set to fill very specific needs.
As this stuff is being added to the main engine it brings more issues, bugs, and possibly breaking other stuff that was working just fine.
For example, the TAG system has some issues opened in this hub, including ones that could be easily fixed by high-level devs with knowledge of ZSS.
https://github.com/Windblade-GR01/Ikemen-GO/issues/216
In this case, as TAG is being treated as a core feature of the engine, the appveyor release includes it which means that for the fix that we need to push the fix on this Github and wait for Gacel to compile.
What if TAG could be simply an external module that can be posted in a repository and every user capable of modifying or fixing it can post its own version, which could be merely a fix or a total remake of the tag code?
We will less dependant on low-level devs who have real-life stuff going outside and the burden for themselves could be much less. So the little time low-level devs have could be invested in helping us on things only they could be able to do.(I know that is the boring part but so far only a hand of users are able to fix/add stuff from the GO part)

Examples of things that should be threatened as external modules.
Delta and Parallax
These things have been very hard to make work as it does on Mugen. I do not know if these features involve touching  Golang code.
Tag and Simul
These modes always break chars, stages, attached cars etc, these modes involve LUA/ZSS/CNS so any troubleshooting can be easily fixed and done by high-level devs.
Special effects for stages.
These can be easily fixed or enhanced by their own creators, from water splash to bonus games.
Extra modes
Kumite, Survival, and other modes can be modules easily since K4thos introduced a way to create our own modes, these modes can be taken from the core and taken as external modules which could serve to isolate bugs related to these modes easily. 

We don't know what real life could bring, so far we only have two low-level devs active while one of these is partially retired after working so hard in the engine last year and the other concentrated on his education. I am not complaining, these guys have done just too much for us.

Thanks for reading.

**Comment by Windblade-GR01** [comment]
On some parts I agree.
Tag problems are char issues not engine issues.

But this like parallax and delta are actually compatibility issues and should be fixed.
