### ISSUE TITLE
Turn off debug mode.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#236]
;----------------This was already done on Ikemen Go 0.96.1 ----------------------------;
The flood for the numpartner,root, and enemy is trying to kill my PC.
Now I'm trying to debug a friend's project with TAG and AI and the game has like 130 chars coming from Winmugen era and the flood is unbearable, mostly on TAG.
Most of the time I put the char I need to debug in the first slot.
So once I press CTRL+D I get the info I need but to turn off the debug that is trying to kill my PC I need to press CTRL+D several times even going through the helpers.
So, what about CTRL+SHIFT+D to turn on/off the debug move no matter what the character is being "debugged".
;------------------------------------------------------------------------------------------------------;

Use Shift+D to turn off debug.

Same for AI, debugging tag and AI pressing ctrl+everynumber, sometimes you have to turn off/on all of them.
Maybe a  CTRL+SHIFT+0 to turn on/off all the AI's in the fight.

Thanks for reading.

**Comment by Windblade-GR01** [comment]
Maybe we could make the error logs toggle separate from the debug toggle.
That way you could enable debug without enabling the logs.

**Comment by Orochikyocr** [comment]
K4thos added a console parameter in the config.json to enable/disable the warning messages and the flood because partner,enemy and root. But it was scrapped on 0.96. 
Still ctrl+shift+d could be useful for chars that have lots of helpers.
Sometimes I just need the stateno and I need to press CTRL+D and pass for every single helper.

Thanks in advance.

**Comment by Orochikyocr** [comment]
K4thos pointed out some got bits about the matter.
Shift+D close the debug mode at once.
Using the debug.def font means less resource usage.
I will leave this open because turn on/off all the AI's.
