### ISSUE TITLE
Chars size in versus

### ISSUE THREAD

**Issue by evildarklxs** [Windblade-GR01/Ikemen-GO#238]
Versus Screen
![ikemen001](https://user-images.githubusercontent.com/78336781/109707499-016b4a80-7b79-11eb-927f-5429f1afd176.png)

Some characters in their .cns have another size, and in the versus they dont read it, the characters are of different sizes

**Comment by K4thos** [comment]
works as expected (same as normal portraits, taking character localcoord into account but ignoring cns [Size] settings). If you need to change portrait scale on per character basis use this feature: https://github.com/K4thos/Ikemen_GO/wiki/Character-features#def_info_portraitscale
