### ISSUE TITLE
Some Stages get messed up

### ISSUE THREAD

**Issue by Mark85Mete** [Windblade-GR01/Ikemen-GO#24]
[https://cdn.discordapp.com/attachments/444327782831357973/579666661687427073/Ikemen_GO_2019-05-19_16-45-43.png](url)

[https://cdn.discordapp.com/attachments/444327782831357973/579666662345801729/Ikemen_GO_2019-05-19_16-44-52.png](url)

[https://cdn.discordapp.com/attachments/444327782831357973/579666682008567818/Ikemen_GO_2019-05-19_16-44-42.png](url)

Can send stages if you wanna see for yourself

**Comment by Windblade-GR01** [comment]
Sending the stages would be very helpful.

**Comment by Windblade-GR01** [comment]
Over here again
To update this:
The third stage does not present the problem described.
The second one, is the fault of the stage.

The first one... I'll investigate more,

Also "Shine of the Forgotten God" stage:
Mugen 1.1: https://i.imgur.com/nK1ehBl.png
Ikemen GO: https://i.imgur.com/bUqlwUH.png

**Comment by Orochikyocr** [comment]
Since 2019 huge improvements have been done to stages. Why not mark this as close and start a new thread if other stages cause issues?

**Comment by waspennator** [comment]
> Since 2019 huge improvements have been done to stages. Why not mark this as close and start a new thread if other stages cause issues?

Dunno about the first 3 stages, but I tested "Shrine of the Forgotten God" again and can confirm the ground position is still acting weird compared to Mugen 1.1
