### ISSUE TITLE
Add better dialogue support for matches with more than 2 players.

### ISSUE THREAD

**Issue by JTDaddy17** [Windblade-GR01/Ikemen-GO#244]
Apparently, the Dialogue feature in Ikemen Go only works for 1v1 matches. However, I'm working on a project that has occasional 2v2 matches and I want the partner fighters to take advantage of this feature too. I would like to see better implementations for the Dialogue feature to let you configure animations for Player 3 and Player 4, using the text box for Player 1 and 2 only is still fine since you can change the names and portraits, but when it comes to animations, that's a different story. Can you please consider adding better support for 2v2 Dialogues? It would help this project of mine a lot!

**Comment by K4thos** [comment]
read the documentation, it already supports unlimited amount of characters via redirections https://github.com/K4thos/Ikemen_GO/wiki/State-controllers#new_dialogue
