### ISSUE TITLE
Hitdef time = 0 breaks TargetState and target()

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#247]
[State 640,HitDef]
type = HitDef
trigger1 = time = 0 ;animelem = 2
attr = A, NA
animtype = Hard
damage    = 70
getpower = 36,36
air.velocity = -3.5,-6
yaccel = .5
ID = 20

Using time = 0 as a trigger for hitdef breaks targetstate and other target triggers as the ID value never get passed to targetstate.

**Comment by Orochikyocr** [comment]
`[State 2, targetstate]
type = targetstate
triggerall = !ishelper
;triggerall = enemynear,var(14)!=2
triggerall = numtarget(20)
triggerall = target(20),alive
trigger1 = target(20),stateno = 5020
trigger1 = target(20),statetype = A
trigger1 = target(20),movetype = H
value = 5470`
This code is inside statedef -2
By adding ignorehitpause = 1 at the end of this state fixed all the states causing the issue event those states still using trigger1 = time = 0.
This wasnt happening on Mugen or any Ikemen Go version previous to 0.96.0.

**Comment by K4thos** [comment]
>  This wasnt happening on Mugen or **any Ikemen Go version previous to 0.96.0**.
doubt, there were no changes even remotely related to this stuff as far as I know. Please upload problematic character that showcases the problem and detailed repo steps how to reproduce it, so that it can be reliably tested in mugen and various ikemen go builds.

**Comment by Orochikyocr** [comment]
Since I wasn't able to reproduce the bug in CNS or ZSS I close this thread. Reported it because this happens in a full game that worked fine in 0.95 and 0.94. I'll fix it locally. Thanks for all your kind attention.
