### ISSUE TITLE
Can't Compile On Parabola Anymore

### ISSUE THREAD

**Issue by EVILEDLIBRE** [Windblade-GR01/Ikemen-GO#248]
Parabola is an arch-based OS.

I used to be able to compile several months ago. But, now it errors out. Here is what I get after running get.sh and then build.sh.

bash build.sh
src/sound.go:10:2: missing go.sum entry for module providing package github.com/Windblade-GR01/go-openal/openal (imported by github.com/Windblade-GR01/Ikemen_GO/src/src); to add:
        go get github.com/Windblade-GR01/Ikemen_GO/src/src
chmod: cannot access './bin/Ikemen_GO_linux': No such file or directory

Am I missing something? Thank you for your help.

**Comment by Windblade-GR01** [comment]
Run get.sh

**Comment by EVILEDLIBRE** [comment]
> Run get.sh

I did run that last time. But, I ran it again. I also downloaded the newest source code as well.

$ bash get.sh
Downloading dependencies...

go get: upgraded github.com/go-gl/glfw/v3.3/glfw v0.0.0-20201108214237-06ea97f0c265 => v0.0.0-20210311203641-62640a716d48
go get: upgraded github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7 => v0.0.0-20210315015930-ae072cafe09d
# github.com/timshannon/go-openal/openal
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:86:149: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcGetError
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:125:100: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCloseDevice
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:131:107: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCreateContext
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:137:110: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetIntegerv
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:142:156: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetInteger
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:163:114: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureCloseDevice
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:171:88: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStart
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:175:86: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStop
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:179:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:183:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:183:179: too many errors
go get: upgraded golang.org/x/image v0.0.0-20200927104501-e162460cd6b5 => v0.0.0-20210220032944-ac19c3e999fb
go get: upgraded golang.org/x/exp v0.0.0-20201008143054-e3b2a7f2fdc7 => v0.0.0-20210220032938-85be41e4509f
go get: upgraded golang.org/x/mobile v0.0.0-20200801112145-973feb4309de => v0.0.0-20210220033013-bdb1ca9a1e08
go get: upgraded golang.org/x/sys v0.0.0-20201126224755-f88b827b861f => v0.0.0-20210403161142-5e06dd20ab57
go get: upgraded github.com/jfreymuth/oggvorbis v1.0.1 => v1.0.3

bash build.sh
src/sound.go:10:2: missing go.sum entry for module providing package github.com/Windblade-GR01/go-openal/openal (imported by github.com/Windblade-GR01/Ikemen_GO/src/src); to add:
        go get github.com/Windblade-GR01/Ikemen_GO/src/src
chmod: cannot access './bin/Ikemen_GO_linux': No such file or directory

**Comment by EVILEDLIBRE** [comment]
> Run get.sh

**Comment by EVILEDLIBRE** [comment]
> Run get.sh

$ bash get.sh
Downloading dependencies...

go get: upgraded github.com/go-gl/glfw/v3.3/glfw v0.0.0-20201108214237-06ea97f0c265 => v0.0.0-20210311203641-62640a716d48
go get: upgraded github.com/go-gl/gl v0.0.0-20190320180904-bf2b1f2f34d7 => v0.0.0-20210315015930-ae072cafe09d
# github.com/timshannon/go-openal/openal
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:86:149: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcGetError
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:125:100: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCloseDevice
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:131:107: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCreateContext
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:137:110: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetIntegerv
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:142:156: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_walcGetInteger
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:163:114: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureCloseDevice
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:171:88: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStart
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:175:86: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureStop
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:179:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:183:179: cannot use _cgo0 (type *_Ctype_struct_ALCdevice_struct) as type *_Ctype_struct_ALCdevice in argument to _Cfunc_alcCaptureSamples
../../go/pkg/mod/github.com/timshannon/go-openal@v0.0.0-20170220204755-e0ed4c67cffe/openal/alcCore.go:183:179: too many errors
go get: upgraded golang.org/x/image v0.0.0-20200927104501-e162460cd6b5 => v0.0.0-20210220032944-ac19c3e999fb
go get: upgraded golang.org/x/exp v0.0.0-20201008143054-e3b2a7f2fdc7 => v0.0.0-20210220032938-85be41e4509f
go get: upgraded golang.org/x/mobile v0.0.0-20200801112145-973feb4309de => v0.0.0-20210220033013-bdb1ca9a1e08
go get: upgraded golang.org/x/sys v0.0.0-20201126224755-f88b827b861f => v0.0.0-20210403161142-5e06dd20ab57
go get: upgraded github.com/jfreymuth/oggvorbis v1.0.1 => v1.0.3

$ bash build.sh
src/sound.go:10:2: missing go.sum entry for module providing package github.com/Windblade-GR01/go-openal/openal (imported by github.com/Windblade-GR01/Ikemen_GO/src/src); to add:
        go get github.com/Windblade-GR01/Ikemen_GO/src/src
chmod: cannot access './bin/Ikemen_GO_linux': No such file or directory

**Comment by Windblade-GR01** [comment]
Oh.
So it seems that it uses the old OpenAL version...
I'll fix is as fast as I can.

**Comment by EVILEDLIBRE** [comment]
> Oh.
> So it seems that it uses the old OpenAL version...
> I'll fix is as fast as I can.

Good to hear. I will try back later then.

**Comment by EVILEDLIBRE** [comment]
Compiling works great now! Thank you for fixing it. I tried both the 0.97.0 release and from the Master Source Code a few minutes ago and both work. Thank you.
