### ISSUE TITLE
Changing MaxHelper in config.json affects playerid()

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#249]
Pretty much the title.
Low maxhelper value.
![image](https://user-images.githubusercontent.com/42851314/113519940-e3fd1800-954c-11eb-929b-7098a4c724c4.png)
High maxhelper value.
![image](https://user-images.githubusercontent.com/42851314/113519941-e95a6280-954c-11eb-89d1-77145e7d515e.png)

Well, this breaks code based on strict playerID triggers!

**Comment by K4thos** [comment]
if this is how it works than it works as expected: https://mugenguild.com/forum/msg.1809328

**Comment by Orochikyocr** [comment]
Damn, that sucks! Thanks for answering.
