### ISSUE TITLE
Training does not air recover with omsby bbtag characters

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen-GO#255]
I've also posted about this on the discord as well but may as well do it here. Training's automatic air recovery does not work with omsby characters which said author has addressed back in December since they have custom fall states to mitigate mugens fall.defenceup https://mugenguild.com/forum/topics/ohmsby-thread-mitsuru-kirijo-quick-update-41921-190755.msg2489787.html#msg2489787

https://streamable.com/krh9hr

**Comment by K4thos** [comment]
from what I understand omsby characters use workarounds which results in this problem and same thing would happen in mugen (correct me if I'm wrong). So in this case I think the ticket should not have "bug" label. And it's also not something that we should maintain in engine.

**Comment by Windblade-GR01** [comment]
Same things happens on Mugen so.
Agreed, this is not a engine problem.
