### ISSUE TITLE
Nasty Story Mode Error

### ISSUE THREAD

**Issue by JTDaddy17** [Windblade-GR01/Ikemen-GO#256]
This error decided to pop up randomly:
[Ikemen.log](https://github.com/Windblade-GR01/Ikemen-GO/files/6370995/Ikemen.log)
I looked everywhere but I'm finding nothing wrong... here's my .lua file:
[adventure.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6370998/adventure.zip)

**Comment by K4thos** [comment]
already solved here: https://discord.com/channels/233345562261323776/282927929548210177/835729216829784064
@JTDaddy17, please close your tickets when they are no longer valid.
