### ISSUE TITLE
0.96.2 & 0.96.2A Broke Round Animations After Round 2

### ISSUE THREAD

**Issue by Retroid84** [Windblade-GR01/Ikemen-GO#259]
The two latest versions have caused a bug with Round animations. Round 1 & 2 show their animations but from Round 3 onwards it does not show them. I tested with an earlier build and it works fine, also copied just the exe from latest updates to an earlier build and it reproduces the issue so has to do with the coding in the exe not the external scripts etc.

**Comment by two4teezee** [comment]
Can you provide your fight.def and fight.sff so I can debug? I've attempted to replicate this issue with three different sets of lifebars and through my own testing but I have not been successful in replicating the bug.

**Comment by two4teezee** [comment]
This is actually related to the final round selection logic. You probably had 2 rounds to win, and at Round 3 it's actually looking for round.final instead of round3. I'm posting a fix for this issue now.

**Comment by two4teezee** [comment]
#261 should resolve the issue.

**Comment by Retroid84** [comment]
[fight.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6488320/fight.zip)

I have attached the fight.def and fight.sff as requested. I have just noticed those last two versions are no longer available so will the issue be fixed in the re-release of 0.96.2? I still have plenty of work to be getting on with so no rush if so I will just wait for it to be reuploaded, thanks.

**Comment by Retroid84** [comment]
[<iframe src="https://drive.google.com/file/d/1jtfBVLcd7VpLuy5Wlnr2yTrQBVG6zxo7/preview" width="640" height="480"></iframe>](url)

**Comment by Windblade-GR01** [comment]
Pushed a fix with #261.
If it still does not work tell me and I'll reopen this.

**Comment by Retroid84** [comment]
Thanks for the fix so soon, it is much appreciated.
