### ISSUE TITLE
[Feature] framespercount trigger

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen-GO#262]
Self explanatory, A trigger to be able to access the framespercount value of the fight.def so you could divide it by TimeRemaining, TimeTotal, or TimeElapsed to get the representative value of the lifebar timer. This would allow people to get said value without hardcoding the framespercount value into the formula.

`(TimeRemaining / FramesPerCount) + 1`

**Comment by K4thos** [comment]
done
