### ISSUE TITLE
Revise the build system with a Makefile.

### ISSUE THREAD

**Issue by Amavect** [Windblade-GR01/Ikemen-GO#266]
The current build system is adequately documented, but cumbersome to set up and relies on a myriad of scripts that are shoved away in the build folder.
I have been working on writing a Makefile to ease cross-platform building and packaging, and providing better build documentation.

- All documentation relating to the build is within README.md instead of shoved away in the wiki. The wiki pages should be removed.
- Instead of directly installing MinGW-w64 on Windows, MSYS2 will be used for building on Windows, simplifying OpenAL installation.
- System-specific configuration files are used, resulting in the `CONF=os make` pattern. This includes the variables defined in the corresponding Make.$CONF file. This leaves cross-compiling from other OSes a possibility, though Linux is currently only supported.
- Go-openal is modified to static-link the Windows executables. This allows us to package all binaries in a single zip file and not worry about distributing DLLs. The OpenAL license needs to be distributed, as a result.
- `CONF=linux make pkg` builds and packages in a single step, which makes a binaries-only zip and an Elecbyte-screenpack zip.
- Docker is not necessary for any steps.

The fork is here:
https://github.com/Amavect/Ikemen-GO

I still have a few finishing touches to make relating to cross-platform build documentation, license documentation, naming the default target, and windres icon files.
Then, full-release testing can begin.

**Comment by Windblade-GR01** [comment]
Docker is currently used for the CI/CD system.
So these could not be removed.

But this is a big improvement over the current .sh based system.
I'll merge it.

And, thanks for of making these. 😄
