### ISSUE TITLE
Storyboards are missing the loop feature for BGM

### ISSUE THREAD

**Issue by Kokorz** [Windblade-GR01/Ikemen-GO#270]
Pretty self explanatory, most other places in the engine have loopstart and loopend parameters (Menus, Stage BGM, etc etc) but Storyboards seem to be the only place where you can't do such a thing.

**Comment by K4thos** [comment]
this is already implemented. Here is a list of all new storyboard parameters: https://github.com/K4thos/Ikemen_GO/wiki/Storyboard-features
