### ISSUE TITLE
0.97 needs glibc 2.32.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#286]
GlibC 2.32 only comes with the latest Ubuntu 21.04 which IIRC is not an LTS release.
20.04 which is the latest LTS counts with GlibC 2.31 and updating it requires an unstable method of compiling and installing.
Ikemen Go 0.97 won't launch on 18.04 or 20.04 because of this.

Just wondering if it is necessary this dependency this much since non-LTS releases are painful and encouraged to be used only by enthusiasts who want to test unstable stuff. 
If you can roll back the dependency to Glibc 2.31 or Glibc 2.27 we can run Ikemen Go in the latest LTS releases of Ubuntu(20.04 and 18.04) and derivatives. Thank you.

Thanks

**Comment by Windblade-GR01** [comment]
I did was not aware of this change.
It was not intentional, I will search what indirect dependency did cause this.

**Comment by Orochikyocr** [comment]
According to Gacel in Discord changes were done in the compiler and the next version will count with a lower Glibc version to allow executing Ikemen Go.
https://discord.com/channels/233345562261323776/233363722934943744/858581698748481536
