### ISSUE TITLE
Can't run after compile in Ubuntu Focal Fossa 20.04/Linux Mint 20.1 Ulyssa LTS here

### ISSUE THREAD

**Issue by GoroDaimon** [Windblade-GR01/Ikemen-GO#290]
here's my log:
https://pastebin.com/mxXkfhhC

here's log of compilation:
https://pastebin.com/Y7AfpbXU

I tried download the release and don't work:
https://github.com/Windblade-GR01/Ikemen-GO/releases
Don't work in wine too.

Sugestion: Create a universal appimage.

**Comment by Windblade-GR01** [comment]
It seems like a GPU problem.
If you change `FontShaderVer` in `config.json` to:
```
	"FontShaderVer": "140",
```
It does work?

> Sugestion: Create a universal appimage.

Yeah I have been looking into that, because cross-repo dependencies can sometimes conflict.

**Comment by GoroDaimon** [comment]
> "FontShaderVer": "140",
It solves my problem. Thanks, but create a AppImage please.

Thank you a lot.

**Comment by Windblade-GR01** [comment]
> It solves my problem

Nice, so it seems it was the GPU.

> I compiled because the Linux version needs GLIBC 2.32

Yeah, in the next release it will use MUSL and AppImage.
Some C dependencies like OpenAL are heavily modied from repo to repo by the maintainers.

**Comment by Windblade-GR01** [comment]
Fixed in newer versions.
