### ISSUE TITLE
misc character crashes

### ISSUE THREAD

**Issue by CitrusHappy** [Windblade-GR01/Ikemen-GO#301]
[one char that crashes](https://mugenarchive.com/forums/downloads.php?do=file&id=58354-beerus-k6666orochi)

happens with deltarune trio and bubsy as well.

[Ikemen.log](https://github.com/Windblade-GR01/Ikemen-GO/files/6796285/Ikemen.log)

**Comment by K4thos** [comment]
you can drag and drop characters to comment window to upload them as part of ticket (MA has limited access on weekend). As for the error, it's a bug in character (wrong syntax), not something that we should fix. In this case most likely extra `,` at the end of reported line (DeltaruneTrio.cns, line 2609)

**Comment by CitrusHappy** [comment]
thats interesting because mugen 1.1 does not crash if incorrect syntax is found. I'm not sure if it would be better or worse to skip over the error in the character or not though.

**Comment by CitrusHappy** [comment]
removing the syntax errors from the char fixes it (SCA,NA,SA,HA,NP,SP,HP,NT,ST,HT, to SCA,NA,SA,HA,NP,SP,HP,NT,ST,HT)
