### ISSUE TITLE
AI bug

### ISSUE THREAD

**Issue by carlosspeed15** [Windblade-GR01/Ikemen-GO#302]
In the beginning, this character was fine and controllable in training mode. However when going to test in watch mode and then heading for playing Arcade mode the AI triggers the character to move on itself. Also it already has a custom AI build.
https://onedrive.live.com/?id=991D3C9698603DD6%215866&cid=991D3C9698603DD6

**Comment by K4thos** [comment]
link to character doesn't work. No need to use external hosting, drag and drop it here in comment,

**Comment by carlosspeed15** [comment]
[Terry_FF3RB.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6805611/Terry_FF3RB.zip
Nvm I got it. Here you go.

**Comment by K4thos** [comment]
fixed
