### ISSUE TITLE
Stages not working

### ISSUE THREAD

**Issue by LasombraDemon** [Windblade-GR01/Ikemen-GO#312]
Two different versions of WH Ryofu stage have elements that break in IKEMEN but display correctly in MUGEN.

https://www.mediafire.com/file/chzd55zip2tf3hr/Wh2Ryofu.7z/file

https://www.mediafire.com/file/o2wrymcqsz17s4y/Wh2JetRyofu.7z/file

Also, I've tested some stages and I think I found some cases of #172 

For instance: https://www.mediafire.com/file/twwqzfvxfexraby/KenStage.7z/file

EDIT: These issues might be related to me changing from 4:3 to another resolution.

**Comment by LasombraDemon** [comment]
Found a possible reason for this: when I commented out the Delta of each portion, the stage worked fine.

For some reason, I think PositionLink in MUGEN overrides the delta parameter, and this is a behaviour IKEMEN does not do.

;[BG 旗]
[BG flag]
type  = anim
actionno = 10
layerno= 0
mask     = 1
;delta = 0.80,0.84
ID = 1
start    = 0,0     ;-154,8
positionlink = 1

;[BG 炎]
[BG flame]
type  = anim
actionno = 20
layerno= 0
mask     = 1
;delta = 0.80,0.84
ID = 1
start    = 0,0     ;-154,8
positionlink = 1

;[BG 水]
[BG water]
type  = anim
actionno = 30
layerno= 0
mask     = 1
;delta = 0.80,0.84
ID = 1
start    = 0,0  ;-154,8
positionlink = 1

**Comment by K4thos** [comment]
this seems to be the source of problem, indeed, since the intended behaviour is even mentioned in Elecbyte docs:

> positionlink = link_flag
>    Set positionlink to 1 to lock this element's position to the position of the element immediately preceding it in the DEF file. If set to 1, the values of the start parameter for the current element are treated as an offset from the previous element's position. **The delta parameter will have no effect in this case**.
