### ISSUE TITLE
Certain stages have broken animations

### ISSUE THREAD

**Issue by LasombraDemon** [Windblade-GR01/Ikemen-GO#313]
I've noticed this in a number of stages. Uploading the ones that fail. I'm honestly not sure about what's causing this one. I think it's related to deltas. It certainly doesn't show like this in any MUGEN version.

![imagen](https://user-images.githubusercontent.com/74574875/127324825-7b5a0b42-edd3-46fd-90ac-796e04a93733.png)

[KenStages.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/6893155/KenStages.zip)

**Comment by K4thos** [comment]
please be more precise. What kind of problem exactly we're seeing here.

**Comment by LasombraDemon** [comment]
These might be related to me changing from 4:3 to another resolution... I'm rechecking. I used to run in 1900x1425, and I changed to 1900x1400, and now I went back to 1900x1425 and this is not a problem any more.

The issue itself: check the two dark vertical lines around the man in the green shirt, those are never shown in MUGEN.

**Comment by K4thos** [comment]
I've reproduced it on 0.97 but can't using latest source code, which means it's already fixed. Ticket can be closed.
