### ISSUE TITLE
Assertspecials weird behavior while being used by attachedchar.

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#322]
https://www.youtube.com/watch?v=F2Ss50N5iUU

https://streamable.com/qbf1nn

You can see bars blinking because nobardisplay is set from the attachedchar. This happens with nomusic too. Most of the time happens when chars on the screen are being hit by certain movements, for example fireballs.

The assertspecial is in a negative state and ignorehitpause 0 or 1 gives the same result. Also used persistent(1).

**Comment by K4thos** [comment]
can't reproduce it
```coffee
[StateDef -2]

ignoreHitPause{
	mapAdd{map: "test"; value: 1}
	if teamSide = 0 {
		assertSpecial{flag: nobardisplay}
		printToConsole{text: "%v, %v, %v, %v, %v"; params: playerID(56),map(test), playerID(57),map(test), playerID(58),map(test), playerID(59),map(test), playerID(getPlayerId(9)),map(test)}
	}
}
```

**Comment by Orochikyocr** [comment]
Moving everything the assertspecial to statedef -4 worked.
