### ISSUE TITLE
I don't know how to put it in 16:10

### ISSUE THREAD

**Issue by Gaelcraft** [Windblade-GR01/Ikemen-GO#325]
What happens is that my 16:10 1440x900 monitor does not look good with Ikemen Go and I do not know if any custom resolution will work and the gpu is integrated graphics and I think it is only in full screen

**Comment by xx1182** [comment]
If you go inside options, then video settings, you can set up a custom resolution and other graphical settings... or there is the usual config file located in the usual folder like the original M.U.G.E.N

**Comment by Windblade-GR01** [comment]
There is also the option of editing `config.json` to set up a 16:10 resoltion.
The values for resolution are `GameWidth` and `GameHeight`.

**Comment by xx1182** [comment]
> There is also the option of editing `config.json` to set up a 16:10 resoltion.
> The values for resolution are `GameWidth` and `GameHeight`.

Excuse me, but where is this config.json located?

**Comment by Windblade-GR01** [comment]
In the `save` folder.

**Comment by Gaelcraft** [comment]
Pero no se cual resolucion poner para que se vea bien

**Comment by Windblade-GR01** [comment]
You can use the native one, 1440x900.

**Comment by Orochikyocr** [comment]
This should be marked as closed.
