### ISSUE TITLE
Mod for versus screen select like kof 98

### ISSUE THREAD

**Issue by leandrooffline** [Windblade-GR01/Ikemen-GO#329]
I do a mod for versus screen select like kof 98 (select position place press a key, 2snd etc.)
If interest I will can give the code for project.

have problem with done.anim comment lines
--anim update
			for side = 1, 2 do
				local done_anim = motif.vs_screen['p' .. side .. '_done_anim']
				if done_anim ~= -1 and confirmed[1] and confirmed[2] and doneonetime[side] == false then
				
					for i = 1, #start.p[side].t_selTemp do
						start.p[side].t_selTemp[i].anim_data = start.f_animGet(start.p[side].t_selTemp[i].ref, side, i, motif.vs_screen, '', '_done', false, false)
						start.p[side].animDelay = 60
						
					end
					doneonetime[side] = true
				end
			end

https://user-images.githubusercontent.com/4389151/129400260-d752fa30-f420-4a99-8bdf-7df725615afa.mp4

My Discord: 
Sir Fanfaron#0082

**Comment by leandrooffline** [comment]
The code
--;===========================================================
--; VERSUS SCREEN
--;===========================================================
local txt_matchNo = main.f_createTextImg(motif.vs_screen, 'match')
local t_txt_nameVS = {}
for i = 1, 2 do
	table.insert(t_txt_nameVS, main.f_createTextImg(motif.vs_screen, 'p' .. i .. '_name'))
end

function start.f_selectChar(player, t)
	for i = 1, #t do
		selectChar(player, t[i].ref, t[i].pal)
	end
end

function start.f_selectVersus(enabled)
	local ok = true
	for _, v in ipairs(start.p[2].t_selected) do
		if start.f_getCharData(v.ref).vsscreen == 0 then
			ok = false
			break
		end
	end
	if not enabled or not ok then
		start.f_selectChar(1, start.p[1].t_selected)
		start.f_selectChar(2, start.p[2].t_selected)
		return true
	else
		local text = main.f_extractText(motif.vs_screen.match_text, matchno())
		txt_matchNo:update({text = text[1]})
		main.f_bgReset(motif.versusbgdef.bg)
		main.f_fadeReset('fadein', motif.vs_screen)
		main.f_playBGM(true, motif.music.vs_bgm, motif.music.vs_bgm_loop, motif.music.vs_bgm_volume, motif.music.vs_bgm_loopstart, motif.music.vs_bgm_loopend)
		start.f_resetTempData(motif.vs_screen, '', false)
		start.f_playWave(getStageNo(), 'stage', motif.vs_screen.stage_snd[1], motif.vs_screen.stage_snd[2])
		local confirmed = {false, false}
		local row = {1, 1}
		
		--
		local conutOrderSelect = {1,1}
		local t_selected_aux = {{}}
		local t_selTemp_aux = {{}}
		
		function table.shallow_copy(t)
		  local t2 = {}
		  for k,v in pairs(t) do
			t2[k] = v
		  end
		  return t2
		end
		for n = 1, 2 do
				t_selected_aux[n] = table.shallow_copy(start.p[n].t_selected)
				t_selTemp_aux[n] = table.shallow_copy(start.p[n].t_selTemp)
		end
		
		--
		local orderTime = 0
		for side = 1, 2 do
			if main.cpuSide[side] or  #start.p[side].t_selected == 1 or (main.coop and (side == 1 or gamemode('versuscoop'))) then --auto selection in case of cpu controlled side, only 1 member or coop team
				start.f_selectChar(side, start.p[side].t_selected)
				confirmed[side] = true
			else --order time multiplier depending on team size
				orderTime = math.max(orderTime, #start.p[side].t_selected)
			end
		end
		orderTime = motif.vs_screen.time_order * orderTime
		local counter = 0 - motif.vs_screen.fadein_time
		local escFlag = false
		local doneonetime = {false,false}
		while true do
			if not escFlag and (esc() or main.f_input(main.t_players, {'m'})) then
				main.f_fadeReset('fadeout', motif.vs_screen)
				escFlag = true
			elseif confirmed[1] and confirmed[2] then
				if main.fadeType == 'fadein' and (counter >= motif.vs_screen.time or (main.f_input({1}, main.f_extractKeys(motif.vs_screen.p1_key_accept)) and (#start.p[1].t_selected == 1 and #start.p[2].t_selected == 1))) then
					main.f_fadeReset('fadeout', motif.vs_screen)
				end
			elseif counter >= motif.vs_screen.time + orderTime then
				for side = 1, 2 do
					if not confirmed[side] then
						start.f_selectChar(side, start.p[side].t_selected)
						confirmed[side] = true
					end
				end
			else
				for side = 1, 2 do
					if not confirmed[side] then
						---
						
						if (main.f_input({side}, main.f_extractKeys(motif.vs_screen['p' .. side .. '_key_accept']))  or counter >= motif.vs_screen.time - motif.vs_screen.time_order ) and conutOrderSelect[side] < #start.p[side].t_selected then
							sndPlay(motif.files.snd_data, motif.vs_screen['p' .. side .. '_cursor_done_snd'][1], motif.vs_screen['p' .. side .. '_cursor_done_snd'][2])
							
							
							--selecionando invert
							table.insert(start.p[side].t_selected, start.p[side].t_selected[1])
							table.remove(start.p[side].t_selected, #start.p[side].t_selected-(#start.p[side].t_selected-1))
							
							table.insert(start.p[side].t_selTemp, start.p[side].t_selTemp[1])
							table.remove(start.p[side].t_selTemp, #start.p[side].t_selTemp-(#start.p[side].t_selTemp-1))
							
							--faz um extra  para fechar o time
							if conutOrderSelect[side] == #start.p[side].t_selected - 1 then
								table.insert(start.p[side].t_selected, start.p[side].t_selected[1])
								table.remove(start.p[side].t_selected, #start.p[side].t_selected-(#start.p[side].t_selected-1))
								
								table.insert(start.p[side].t_selTemp, start.p[side].t_selTemp[1])
								table.remove(start.p[side].t_selTemp, #start.p[side].t_selTemp-(#start.p[side].t_selTemp-1))

								start.f_selectChar(side, start.p[side].t_selected)
								confirmed[side] = true
								if confirmed[side % 2 + 1] and counter < motif.vs_screen.time - motif.vs_screen.time_order then
									counter = motif.vs_screen.time - motif.vs_screen.time_order 
								end
							end
							row[side] = row[side] + 1 
							conutOrderSelect[side] = conutOrderSelect[side] + 1
						elseif main.f_input({side}, main.f_extractKeys(motif.vs_screen['p' .. side .. '_key_orderup'])) then
							sndPlay(motif.files.snd_data, motif.vs_screen['p' .. side .. '_cursor_move_snd'][1], motif.vs_screen['p' .. side .. '_cursor_move_snd'][2])
							local t_selTemp = {}
							local t_selected = {}
							
							t_selected = start.p[side].t_selected
							t_selTemp = start.p[side].t_selTemp
											
							table.insert(t_selected, #t_selected + 2 - row[side] ,t_selected[1])
							table.remove(t_selected, 1)
							
							table.insert(t_selTemp, #t_selTemp + 2 - row[side] ,t_selTemp[1])
							table.remove(t_selTemp, 1)
							
							start.p[side].t_selected = t_selected
							start.p[side].t_selTemp = t_selTemp	
							
						 elseif main.f_input({side}, main.f_extractKeys(motif.vs_screen['p' .. side .. '_key_orderdown'])) then
							sndPlay(motif.files.snd_data, motif.vs_screen['p' .. side .. '_cursor_move_snd'][1], motif.vs_screen['p' .. side .. '_cursor_move_snd'][2])
							local t_selTemp = {}
							local t_selected = {}
							
							t_selected = start.p[side].t_selected
							t_selTemp = start.p[side].t_selTemp
							
							
							table.insert(t_selected, 1,t_selected[#t_selected + 1 - row[side]])
							table.remove(t_selected,#t_selected+1-row[side])
							
							table.insert(t_selTemp, 1,t_selTemp[#t_selTemp + 1 - row[side]])
							table.remove(t_selTemp,#t_selTemp+1-row[side])
														
																			
							start.p[side].t_selected = t_selected
							start.p[side].t_selTemp = t_selTemp	
							
							
						end	
					end
				end
			end
			counter = counter + 1
			--draw clearcolor
			clearColor(motif.versusbgdef.bgclearcolor[1], motif.versusbgdef.bgclearcolor[2], motif.versusbgdef.bgclearcolor[3])
			--draw layerno = 0 backgrounds
			bgDraw(motif.versusbgdef.bg, false)
			
			--anim update
			for side = 1, 2 do
				local done_anim = motif.vs_screen['p' .. side .. '_done_anim']
				if done_anim ~= -1 and confirmed[1] and confirmed[2] and doneonetime[side] == false then
				
					for i = 1, #start.p[side].t_selTemp do
						start.p[side].t_selTemp[i].anim_data = start.f_animGet(start.p[side].t_selTemp[i].ref, side, i, motif.vs_screen, '', '_done', false, false)
						start.p[side].animDelay = 60
						
					end
					doneonetime[side] = true
				end
			end
			--main.f_printTable(start.p[1].t_selTemp[1].anim_data, 'debug/t_selTemp1.txt')
			--draw portraits
			for side = 1, 2 do
				start.f_drawPortraits(start.p[side].t_selTemp, side, motif.vs_screen, '', false)				
			end
			
			--draw names
			for side = 1, 2 do
				start.f_drawNames(
					start.p[side].t_selTemp,
					t_txt_nameVS[side],
					false,
					false,
					motif.vs_screen['p' .. side .. '_name_font'],
					motif.vs_screen['p' .. side .. '_name_pos'][1] + motif.vs_screen['p' .. side .. '_name_offset'][1],
					motif.vs_screen['p' .. side .. '_name_pos'][2] + motif.vs_screen['p' .. side .. '_name_offset'][2],
					motif.vs_screen['p' .. side .. '_name_font_scale'][1],
					motif.vs_screen['p' .. side .. '_name_font_scale'][2],
					motif.vs_screen['p' .. side .. '_name_font_height'],
					motif.vs_screen['p' .. side .. '_name_spacing'][1],
					motif.vs_screen['p' .. side .. '_name_spacing'][2],
					motif.vs_screen['p' .. side .. '_name_active_font'],
					row[side]
				)
			end
			--restaura padrão  do time
			--if counter >= motif.vs_screen.time  + motif.vs_screen.fadeout_time then
			if main.fadeType == 'fadeout' and
			counter >= motif.vs_screen.time  + motif.vs_screen.fadeout_time - 1
			then
				for side = 1, 2 do
						start.p[side].t_selected = t_selected_aux[side]
						start.p[side].t_selTemp = t_selTemp_aux[side] 				
				end
			end
			--
			
			--draw match counter
			if matchno() > 0 then
				txt_matchNo:draw()
			end
			--draw layerno = 1 backgrounds
			bgDraw(motif.versusbgdef.bg, true)
			--draw fadein / fadeout
			main.f_fadeAnim(motif.vs_screen)
			--frame transition
			if not main.f_frameChange() then
				clearColor(motif.versusbgdef.bgclearcolor[1], motif.versusbgdef.bgclearcolor[2], motif.versusbgdef.bgclearcolor[3]) --skip last frame rendering
				break
			end
			main.f_refresh()
		end
		esc(escFlag) --force Esc detection
		return not escFlag
	end
end

**Comment by K4thos** [comment]
0.98 will have kof style order selection by default: https://github.com/K4thos/Ikemen_GO/wiki/Miscellaneous-Info#orderselect (not based on your code but similar functionality)

**Comment by Orochikyocr** [comment]
This should be marked as closed since it was already implemented.
