### ISSUE TITLE
Tag animations glitching

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#334]
https://user-images.githubusercontent.com/77592586/129966244-255b5507-a617-4b63-9b06-965e29806af5.mp4
First for some reason Rock disappears when tagged out, doesn't really make any sense to me since he uses the exact same animation for tag in.

https://user-images.githubusercontent.com/77592586/129966468-974f57c6-706e-433b-acb5-565817bea04e.mp4
Second Iori's jump in goes through the floor.

Characters: 
[Iori.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7009989/Iori.zip)
[Rock.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7009992/Rock.zip)

**Comment by K4thos** [comment]
none of these happens on upcoming 0.98 build, which means it's already fixed by recent tag related commits. Ticket can be closed.
