### ISSUE TITLE
Victory screen not showing up on Turns mode if the match is decided by a draw.

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#337]
https://user-images.githubusercontent.com/77592586/130309435-b825aadc-29ba-4cc6-9c30-7dabd1d3394e.mp4

Since K' is the last character the victory should go to Kyo's team but the victory screen doesn't show up and it just goes back to char select.

**Comment by K4thos** [comment]
already fixed
