### ISSUE TITLE
[Feature] Stage transition

### ISSUE THREAD

**Issue by pidgeon777** [Windblade-GR01/Ikemen-GO#34]
It would be great to load stages so that when a certain action happens during a match, then the game would switch to another stage.

For example, consider Mortal Kombat. When doing a uppercut, the stage changes:

https://www.youtube.com/watch?v=YgX_jpC6cz4

Do you think it would be doable in Ikemen GO?

Congratulations though and keep it up!

**Comment by Windblade-GR01** [comment]
It is posible via the MatchRestart command. (If you want to use different stage def files)
The limitation with that is that it can be done between rounds.

If you want to do it dynamically (Mid match) it could be done with Attachedchar (The Ikemen way of doing interactive stages)

These could be found at NeatUnsou (A Ikemen Go dev) ReadMe:
https://osdn.net/users/neatunsou/pf/ikemen_go/wiki/FrontPage
It's in Japanese, I should translate it and add it to the Github ReadMe.

**Comment by pidgeon777** [comment]
Thank you for the informative reply. My idea is to some interesting things with your modded engine in the upcoming months, thus I should be able to report some issues if present. Anyway, I'm really interested in your project and I wish you success.

**Comment by Mike77154** [comment]
Remember that You can get a little help of the electro Interactive mugen pack for codding some variations

**Comment by K4thos** [comment]
I think this feature request can be considered fulfilled. Relevant features that allows this functionality:
- https://github.com/K4thos/Ikemen_GO/wiki/Stage-features#info_attachedchar
- https://github.com/K4thos/Ikemen_GO/wiki/State-controllers#new_modifybgctrl
