### ISSUE TITLE
About DefenceMulSet

### ISSUE THREAD

**Issue by PsyXENOS** [Windblade-GR01/Ikemen-GO#342]
Currently, the DefenceMulSet is not functioning properly. 
It should be hardened at the decimal point, but the damage it takes is getting bigger. 
This affects many characters and should be fixed as soon as possible.

(This is my first time using this place. I'm sorry if I'm using it wrong.)

**Comment by Windblade-GR01** [comment]
Fixed, the fix will come in the new versions.
**PS:** You used it will.
