### ISSUE TITLE
[FEATURE REQUEST] The ability to unselect a character without exiting to menu

### ISSUE THREAD

**Issue by Acj-One** [Windblade-GR01/Ikemen-GO#352]
i noticed this engine has and is adding a lot of quality of life features (like a  pause menu, the ability to pick colors from a menu, functioning training mode, etc)
i was just wondering, were there any plans to add the ability to go back after picking a character? like, the ability to change your mind and pick someone else without having to exit to the menu?

**Comment by Orochikyocr** [comment]
https://github.com/Windblade-GR01/Ikemen-GO/issues/128
This should be merged with this. Duplicated.
