### ISSUE TITLE
Victory Screen not Show in Turns mode

### ISSUE THREAD

**Issue by leandrooffline** [Windblade-GR01/Ikemen-GO#358]
Main Build 2021-09-26
Test in Team Arcade

https://user-images.githubusercontent.com/4389151/134807803-dd3df8a2-5f69-44df-baa8-b39ac7f0cc70.mp4

**Comment by K4thos** [comment]
fixed, thanks

**Comment by leandrooffline** [comment]
Nice!!! Thank you.
