### ISSUE TITLE
Mugen 1.1 MVC2 lifebars do not work correctly

### ISSUE THREAD

**Issue by Junny4444** [Windblade-GR01/Ikemen-GO#360]
[XX'MVC2'BARS'XX.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7246062/XX.MVC2.BARS.XX.zip)

These lifebars do not work correctly as shown here: https://i.imgur.com/qJkzL60.png

The names do not show correctly and it always says the character have max power bar when the character actually only have 1 power bar.

**Comment by K4thos** [comment]
works correctly in upcoming 0.98

![ikemen026](https://user-images.githubusercontent.com/8928195/135157393-17ce5aeb-8306-4d20-be37-d76c764ef5b4.png)
:

**Comment by Junny4444** [comment]
nice

**Comment by sevasesino** [comment]
hola quiero saber si se puede o hay una versión de ikemen go o mugen para Xbox 360 es que tengo una y quiero jugar con mi padre esos buenos momento recordarle la nostalgia esos bueno momento y yo también, porfa ayuda
