### ISSUE TITLE
bug in ikemen go v0.97.0 "failed to compile #version 150 core"

### ISSUE THREAD

**Issue by Deudro** [Windblade-GR01/Ikemen-GO#376]
I see that there is only a solution for linux, won't there be a solution in windows?

my computer has opengl 2.1, and when I try to open ikemen go, I get a white screen for a few seconds and it closes.

try changing `"FontShaderVer": "150 core"` to `"FontShaderVer": "120 core"` but it doesn't work; then I put a dll that simulates the latest version of opengl, and I get the same error for core version.

the dll that simulates the latest version is not the problem, because it has always worked for me.

so if someone can help me with the problem in windows it would be great 

Log:

failed to compile #version 150 core

//vertex position
in vec2 vert;

//pass through to fragTexCoord
in vec2 vertTexCoord;

//window res
uniform vec2 resolution;

//pass to frag
out vec2 fragTexCoord;

void main() {
   // convert the rectangle from pixels to 0.0 to 1.0
   vec2 zeroToOne = vert / resolution;

   // convert from 0->1 to 0->2
   vec2 zeroToTwo = zeroToOne * 2.0;

   // convert from 0->2 to -1->+1 (clipspace)
   vec2 clipSpace = zeroToTwo - 1.0;

   fragTexCoord = vertTexCoord;

   gl_Position = vec4(clipSpace * vec2(1, -1), 0, 1);
} : 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
  
goroutine 1 [running, locked to thread]:
github.com/yuin/gopher-lua.(*LState).PCall.func1(0xd81840, 0x21c62000, 0x23365bc0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:1988 +0x517
panic(0xd06220, 0x226ffca0)
	/usr/lib/go-1.15/src/runtime/panic.go:969 +0x119
github.com/ikemen-engine/glfont.LoadFont(0x2224cfc0, 0x23, 0x1b, 0x140, 0xf0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ikemen-engine/glfont@v0.0.0-20210605001652-702569ee65fb/font.go:48 +0x2d8
main.loadFntTtf(0x230be9b0, 0x230c8280, 0x12, 0x230ca202, 0x1e, 0x1b)
	/ikemen/src/font.go:340 +0x117
main.loadDefInfo(0x230be9b0, 0x230c8280, 0x12, 0x23365690, 0xffffffff)
	/ikemen/src/font.go:314 +0x354
main.loadFntV2(0x230c8280, 0x12, 0xffffffff, 0x1003100, 0x1000000, 0x0)
	/ikemen/src/font.go:275 +0x25a
main.loadFnt(0x21fcc8b0, 0xd, 0xffffffff, 0xd, 0x3f0088, 0x0)
	/ikemen/src/font.go:49 +0x63
main.systemScriptInit.func53(0x21c62000, 0x38d)
	/ikemen/src/script.go:766 +0x71
github.com/yuin/gopher-lua.callGFunction(0x21c62000, 0x0, 0x21e27ae0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:202 +0x31
github.com/yuin/gopher-lua.init.3.func26(0x21c62000, 0x7c100403, 0x21c64050, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:821 +0x34a
github.com/yuin/gopher-lua.mainLoop(0x21c62000, 0x21c64050)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:31 +0xc6
github.com/yuin/gopher-lua.(*LState).callR(0x21c62000, 0x1, 0x1, 0x17)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:1211 +0x18b
github.com/yuin/gopher-lua.(*LState).Call(...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:1967
github.com/yuin/gopher-lua.loRequire(0x21c62000, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/baselib.go:559 +0x456
github.com/yuin/gopher-lua.callGFunction(0x21c62000, 0x0, 0x21c31e00)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:202 +0x31
github.com/yuin/gopher-lua.init.3.func26(0x21c62000, 0x7c500402, 0x21c64000, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:821 +0x34a
github.com/yuin/gopher-lua.mainLoop(0x21c62000, 0x21c64000)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/vm.go:31 +0xc6
github.com/yuin/gopher-lua.(*LState).callR(0x21c62000, 0x0, 0xffffffff, 0x0)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:1211 +0x18b
github.com/yuin/gopher-lua.(*LState).Call(...)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:1967
github.com/yuin/gopher-lua.(*LState).PCall(0x21c62000, 0x0, 0xffffffff, 0x0, 0xe039a0, 0x230ade40)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/state.go:2030 +0xe1
github.com/yuin/gopher-lua.(*LState).DoFile(0x21c62000, 0x21d6a5a0, 0x18, 0x21c62000, 0x1)
	/root/go/pkg/mod/github.com/yuin/gopher-lua@v0.0.0-20210529063254-f4c35e4016d9/auxlib.go:396 +0x93
main.main()
	/ikemen/src/main.go:87 +0x198

stack traceback:
	[G]: in function 'fontNew'
	external/script/main.lua:413: in function <external/script/main.lua:388>
	(tailcall): ?
	.\external\script\menu.lua:374: in function <.\external\script\menu.lua:0>
	[G]: in function 'require'
	external/script/main.lua:2133: in main chunk
	[G]: ?

**Comment by EVILEDLIBRE** [comment]
@Deudro 
The new stable release is out now. You should try that as the bug should be fixed there. Please report back your results.

**Comment by Orochikyocr** [comment]
This should be marked as CLOSED.
