### ISSUE TITLE
Info display for training mode. 

### ISSUE THREAD

**Issue by Orochikyocr** [Windblade-GR01/Ikemen-GO#381]
I made much stuff for Ikemen Go, some modules here and there, but I always thought my stuff is not for everybody.

This time I took some time to code the info display from the scratch for 0.98 now that we can render text. I don't know if low-level devs have something prepared already but if it is not the case I would like to introduce what I have done so far and I think it would be useful for everybody. It is not finished but since it is the first time I proposed something of mine to be integrated with the engine I would like to know at least if the code is decent enough.
[trainingdisplayinfo.zss.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7447931/trainingdisplayinfo.zss.zip)

I am using the same items Stupa used plus Juggle, which is not working because I don't know how to use jugglepoints trigger yet.

You can see it working here.
https://streamable.com/vvr5e0

So if you think it is useful for you, please use it freely. Have a good day.

**Comment by Orochikyocr** [comment]
I am aware that I am in favor of keeping the engine as simple as possible. However, I consider that now all the fighting games since ten years ago now have an info display for the training mode. However, if this is deemed unnecessary, I understand perfectly.

**Comment by K4thos** [comment]
it's useful but there are 2 other people that already signaled indentation to implement it. two4teezee (not sure if he finished it,  worth checking his github) and Kamekaze (who said that his version fixed all issues that strupa training had with counting adv frames correctly). It would be great if you guys collaborate to contribute the best version out of your work (and ideally the simplest solution, commented and written in a way that is self-explanatory, like the rest of trainning.zss).

btw. your trainingdisplayinfo.zss.zip archive is empty.

**Comment by Orochikyocr** [comment]
Damn, sorry for the empty file.

https://pastebin.com/HCi7GA69

Here on Pastebin.

If kame is already over the issue I think I can't do that much. My advframe calculation differs from Stupa by 1 frame. Thanks for the answer.
