### ISSUE TITLE
video feature for intros/backgrounds etc - no more only frames/photos

### ISSUE THREAD

**Issue by Splashslash** [Windblade-GR01/Ikemen-GO#386]
Dont know if will be possible. So, this is a sugestion to screenpacks

**Comment by Orochikyocr** [comment]
Bro, this has been already suggested.

https://github.com/Windblade-GR01/Ikemen-GO/issues/355

Bump into that thread and say you also would like this to be implemented.

**Comment by Splashslash** [comment]
Thank you friend for advice. sorry for reopen that.

**Comment by Orochikyocr** [comment]
No worries.
