### ISSUE TITLE
HP recovery not working in turns mode.

### ISSUE THREAD

**Issue by trackiesthead** [Windblade-GR01/Ikemen-GO#391]
Hi, I'm having an issue with my IKEMEN V0.98 install where, no matter the settings, the characters never recover their HP after finishing rounds in turns. If it helps, this is what **config.json** delivers.

"RatioRecoveryBase": 20,
  "RatioRecoveryBonus": 30,
  "RoundsNumSimul": 2,
  "RoundsNumSingle": 2,
  "RoundsNumTag": 2,
  "RoundTime": -1,
  "ScreenshotFolder": "",
  "StartStage": "stages/stage0-720.def",
  "StereoEffects": true,
  "System": "external/script/main.lua",
  "Team1VS2Life": 300,
  "TeamDuplicates": false,
  "TeamLifeShare": false,
  "TeamPowerShare": true,
  "TrainingChar": "",
  "TurnsRecoveryBase": 30,
  "TurnsRecoveryBonus": 40,
  "VolumeBgm": 80,
  "VolumeMaster": 80,
  "VolumeSfx": 80,
  "VRetrace": 0,
  "WindowIcon": [
    "external/icons/IkemenCylia_256.png",
    "external/icons/IkemenCylia_96.png",
    "external/icons/IkemenCylia_48.png"
  ],

It may be just a misconfiguration but since I'm still new with IKEMEN I would like some enlightment here.

**Comment by K4thos** [comment]
can't reproduce
