### ISSUE TITLE
Lifebars using "px.face.layerno" on [Face] no longer share palettes.

### ISSUE THREAD

**Issue by DolphinDan400** [Windblade-GR01/Ikemen-GO#395]
A lifebar I made in version 0.97.0 can no longer use the character palette for the portraits in 0.98.1 even after double checking everything on the .def file.
After experimenting with them and the default ones bundled in I found that applying px.face.layerno = 1 to [Face] breaks the palette sharing and always uses the default one instead, I also tried using pX.face.palshare but to no results, here's a demonstration with the portraits moved down to show the issue.
![layerbug](https://user-images.githubusercontent.com/94821269/142807858-92c128af-c961-4fac-9a40-0b17aeacc444.png)

**Comment by K4thos** [comment]
fixed, thanks
