### ISSUE TITLE
launchFight p1char[slotNum] issues(?)

### ISSUE THREAD

**Issue by GodzillaFightn** [Windblade-GR01/Ikemen-GO#398]
Currently I'm trying to make a full-game using v0.98.1, and I plan for a predetermined character to assist you against the final boss of **Arcade** mode, as a Simul char (so he has his own health, power, etc, while also being on your side of the lifebars), so I am trying to use p1char[2] to change only Player3.
However, every time I try to use it, it just crashes upon the match attempting to load.

It _should_ be very easy to reproduce this, by simply putting this in a file, and putting it in a characters arcadepath.

if matchno() == 1 then
	if not launchFight{
	p1teammode = "simul",
	p1char[2] = {"kfm"}
	} then return end
end
setMatchNo(-1)

Doing this (or something similar like p1char[2] = "kfm", p1char["2"], p1char[slot2], etc) just crashes the game upon it trying to load the match.

.\external\script\start.lua:1451: data/arcadetest.lua line:5(column:12) near '=':   syntax error

stack traceback:
	[G]: in function 'assert'
	.\external\script\start.lua:1451: in function 'f'
	external/script/main.lua:3019: in function 'loop'
	external/script/main.lua:3103: in function 'loop'
	external/script/main.lua:4081: in main chunk
	[G]: ?

Am I _horribly_ misunderstanding the Wiki's launchFight instructions on [slotNum], or was it unimplemented or removed at some point?
I've been struggling with this for far too many hours straight and I'm just about ready to give up and just make the assist character Player4 with a special version that only hits its teammates (aka: the boss), as much as it would pain me to do so.

I honestly wouldn't even be mad at this point to just be told "you just have to type it like this instead" and it _work_.

**Comment by K4thos** [comment]
That part about indexing is wrong (you're trying to index a table that doesn't exist yet). I've just removed it from wiki. Will think how to make accessing this data easier in future. For now (and this solution will stay regardless, since that's how this data is stored internally) you can retrieve selected p1 character def file name via:
```lua
start.f_getCharData(start.p[1].t_selected[1].ref).char
```
so in your example it can be:
```lua
if matchno() == 1 then
	if not launchFight{
		p1teammode = "simul",
		p1char[2] = {start.f_getCharData(start.p[1].t_selected[1].ref).char, "kfm"}
	} then return end
end
```

**Comment by GodzillaFightn** [comment]
Ah, I see. Thanks for the info, and for the speed of that response!
I think I tried to do something similar to that before, but couldn't figure out how...
