### ISSUE TITLE
Downed characters on tag mode being hit.

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#402]
https://user-images.githubusercontent.com/77592586/145503379-1b5413a4-c1ed-4ac3-a5b0-9172654d9daf.mp4

Some moves like Kim's heavy stomp hits downed characters.

[Kim.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7689531/Kim.zip)

Move mentioned is : DD+heavy kick.

**Comment by K4thos** [comment]
this will no longer happen in 0.98.2: https://github.com/K4thos/Ikemen_GO/commit/90048bc831b9269cec801e8620dbeaf884aa78a3
