### ISSUE TITLE
Problems with stages on the new version

### ISSUE THREAD

**Issue by Reystlin** [Windblade-GR01/Ikemen-GO#406]
Test on 0.98.1:
CVS2_Burning_Osaka.def
![ikemen000 CVS2_Burning_Osaka](https://user-images.githubusercontent.com/18099200/146166015-ba38e45a-7bce-4a08-8346-962eb633ac53.png)
cvs2_stadium.def
![ikemen000 cvs2_stadium](https://user-images.githubusercontent.com/18099200/146166269-972a8a8f-1137-45b5-a4e9-229711561bd8.png)
cvs2_Barentsburg.def
![ikemen000 cvs2_Barentsburg](https://user-images.githubusercontent.com/18099200/146166415-e30a01d1-8c90-4d11-915e-fa18e7e401fa.png)
![ikemen001 cvs2_Barentsburg](https://user-images.githubusercontent.com/18099200/146166445-6d5827cb-dfff-4111-8304-d769829f7c64.png)

Test on 0.98.2-RC2:
CVS2_Burning_Osaka.def
![ikemen000 CVS2_Burning_Osaka](https://user-images.githubusercontent.com/18099200/146166548-ccad3745-c281-48bb-81ee-620744459991.png)
cvs2_stadium.def
![ikemen000 cvs2_stadium](https://user-images.githubusercontent.com/18099200/146166613-aedfc25c-9f4a-4067-8021-6b3ca224c6cc.png)
cvs2_Barentsburg.def
![ikemen000 cvs2_Barentsburg](https://user-images.githubusercontent.com/18099200/146166664-81968007-1091-4d26-add9-9112a02b63b1.png)
![ikemen001 cvs2_Barentsburg](https://user-images.githubusercontent.com/18099200/146166674-e576212d-0d88-4675-ae29-b0e256fbe7a2.png)

**Comment by K4thos** [comment]
post links to those stages

**Comment by Reystlin** [comment]
[cvs2_Barentsburg.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7718299/cvs2_Barentsburg.zip)
[CVS2_Burning_Osaka.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7718301/CVS2_Burning_Osaka.zip)
[cvs2_stadium.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/7718305/cvs2_stadium.zip)

**Comment by K4thos** [comment]
thanks, will be fixed soon

**Comment by K4thos** [comment]
fixed, thanks

**Comment by K4thos** [comment]
fixed, thanks
