### ISSUE TITLE
Palfx on explods

### ISSUE THREAD

**Issue by Eiton** [Windblade-GR01/Ikemen-GO#407]
Open an issue here since my question posted on mugen guild is not answered.
Is the repo accepting PR on adding features for sctrls?
I cloned the repo and added palfx parameters for Explod (like the parameters in hitdef).
I was forced to write the following code to change the color of the explod in Mugen 1.1 but I don't want to do this in IKEMEN
```
[Statedef 200]
...
[State 0]
type = Helper
trigger1 = AnimElem = 4
stateno = 6000
ownpal = 1
...
[Statedef 6000]
...
[State 0, PalFX]
type = PalFX
trigger1 = !time
time = -1
mul = r,g,b
 
[State 0]
type = Explod
trigger1 = !time
anim = 6000
ID = 6000
pos = 0,0
ownpal = 0
...
 
[State 0, DestroySelf]
type = DestroySelf
trigger1 = time > 0 && !numExplod
removeexplods = 1
```
Also a bug report.
The above code works fine in mugen 1.1 but not in IKEMEN (0.98.1).  The color of the explod is not changed when time = 0. I need to change it to the following in order to get it work.
```[Statedef 200]
...
[State 0]
type = Helper
trigger1 = AnimElem = 4,=-1
stateno = 6000
pos = 0,0
ownpal = 1
...
[Statedef 6000]
...
[State 0, PalFX]
type = PalFX
trigger1 = !time
time = -1
mul = r,g,b
 
[State 47]
type = Explod
trigger1 = time = 1
anim = 6000
ID = 6000
pos = 0,0
ownpal = 0
...
 
[State 0, DestroySelf]
type = DestroySelf
trigger1 = time > 0 && !numExplod
removeexplods = 1
```

**Comment by K4thos** [comment]
> Open an issue here since my question posted on mugen guild is not answered.
sorry, we're not that active on MFG. Consider joining discord: https://discord.gg/XNbRqHM

> Is the repo accepting PR on adding features for sctrls?
contributions are welcome but can't say I like this particular idea. In zss, your example code can be written like this:
```cofee
palFX{time: -1; mul: r,g,b}
explod{anim: 6000; id = 6000; pos: 0,0; ownpal: 0}
```
so total space saved by adding palFX parameters to explod is 1 line. In cns it requires few more lines, but it's still not much of a difference. Other than this there is 0 added value (unless I'm missing something)

As for the difference between mugen and ikemen, yeah, it should be logged as bug (backward compatibility problem). Thanks for reporting.

**Comment by K4thos** [comment]
> Open an issue here since my question posted on mugen guild is not answered.

sorry, we're not that active on MFG. Consider joining discord: https://discord.gg/XNbRqHM

> Is the repo accepting PR on adding features for sctrls?

Before implementing new feature it's better to gather feedback and discuss it on discord, but yes, we're open for contributions.

**Comment by Eiton** [comment]
I would say the major purpose of adding this is to reduce helper usage.

Also, the above method doesn't work when you want the explod to pause when the player is in hit pause.
