### ISSUE TITLE
Music on Different rounds like in 3rd Strike

### ISSUE THREAD

**Issue by jankespro12** [Windblade-GR01/Ikemen-GO#415]
In Round 1, it plays the first music, in round 2, Plays the second one. and on the final round, it will play the final music like in 3rd Strike Home Ports,

**Comment by K4thos** [comment]
already implemented (will be in 0.98.2) https://github.com/K4thos/Ikemen_GO/commit/3fe1a046eab790bd6fb88c42b104c1453616507c

**Comment by jankespro12** [comment]
Thanks

**Comment by EgyLynx** [comment]
Why i am hear my midis?
