### ISSUE TITLE
bug on shadow

### ISSUE THREAD

**Issue by brokenstar054** [Windblade-GR01/Ikemen-GO#417]
Hello, I found a shadow rendering bug about Ikemen go
In MUGEN 1.1
![bandicam 2022-01-02 22-27-02-955](https://user-images.githubusercontent.com/96985004/147879720-3bafd2e7-1498-48b7-96cb-d654d5a962ca.jpg)
In IKEMEN GO
![bandicam 2022-01-02 22-35-04-903](https://user-images.githubusercontent.com/96985004/147879376-bdbb6768-f5c1-44e0-8393-5824f91cdc6d.jpg)
The transparent part of the image has also been rendered, and the whole shadow has become a large shadow block. I hope this feedback can be noticed. Because I can't speak English, I can only use machine translation. I'm sorry for this.

**Comment by brokenstar054** [comment]
Because the zip file is too large to upload to GitHub, I can only upload the file in this way. I'm sorry about this.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Windblade-GR01/Ikemen-GO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月10日(星期一) 晚上7:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Windblade-GR01/Ikemen-GO] bug on shadow (Issue #417)





 
when reporting bugs please always upload problematic content (drag and drop zip directly to your message to upload it on github). Screenshot is almost never enough to reproduce problem.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

AK-Skadi_20211007_231313.zip (137.47M, 2022年02月09日 20:23 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=68393636145d0d95dc9ae2901037574d010c53060f06505014580254501a515b0b0c1b0e0e52514f5d5c02500f0e0053005a5004362b65237214655d57530c3d0b09040707075555660b05070506564c435046360b&code=996667eb

**Comment by K4thos** [comment]
I've noticed that this has been already reported, so this ticket can be closed (1 ticket per bug)
https://github.com/Windblade-GR01/Ikemen-GO/issues/142
youtube video in that ticket links to a character that has this problem.

**Comment by K4thos** [comment]
thanks for uploading character. Problem should be fixed in next build

**Comment by brokenstar054** [comment]
That's great. Thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Windblade-GR01/Ikemen-GO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 凌晨2:58
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Windblade-GR01/Ikemen-GO] bug on shadow (Issue #417)





 
thanks for uploading character. Problem should be fixed in next build
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by brokenstar054** [comment]
Hello, me&nbsp;again.&nbsp;our team has made a game with Ikemen go, but its loading speed is very slow due to resource occupation, so we would like to ask if there is any optimization method. In other words, is there anything that can be modified in the engine. In order to make the problem description more specific, a game compression package has been attached.Because I can't speak English, I can only use machine translation.&nbsp;I'm sorry if it bothers you.
从QQ邮箱发来的超大附件

ARKNIGHTS FIGHT 潮升.rar (2.05G,  到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7a6238365bd0dd19d2c1ec901338514a045500040108535c1a525b000515575d0456150f0759014802560005575a575755530b02352063246529767f72703736172471717d6c43d686abc518475911650a&t=exs_ftn_download&code=7b8658ce
