### ISSUE TITLE
pal.defaults = 0 crashes the game

### ISSUE THREAD

**Issue by DolphinDan400** [Windblade-GR01/Ikemen-GO#419]
Having "pal.defaults = 0" in the character .def file (for example all of Ryo2005's character) will crash the game if encountered during Arcade Mode, this doesn't happen during Versus Mode or if you pick the character yourself.
Mugen 1.0 & 1.1 doesn't have any issue with this so maybe some sort of fail-safe could be added.

Log:
.\external\script\start.lua:2752: 
Invalid palette: 0

stack traceback:
	[G]: in function 'selectChar'
	.\external\script\start.lua:2752: in function 'f_selectVersus'
	.\external\script\start.lua:1805: in function 'launchFight'
	external/script/default.lua:20: in function <external/script/default.lua:0>
	.\external\script\start.lua:1451: in function 'f'
	external/script/main.lua:3019: in function 'loop'
	external/script/main.lua:3103: in function 'loop'
	external/script/main.lua:4081: in main chunk
	[G]: ?

**Comment by K4thos** [comment]
fixed, thanks
