### ISSUE TITLE
Stage BGCtrl behavior is incorrect

### ISSUE THREAD

**Issue by AshtonTurner** [Windblade-GR01/Ikemen-GO#454]
In mugen the stage provided looks as it should, but as of .98.2 released yesterday this stage loads multiple copies of the wrong element because its not ignoring parameters the type of bgctrl doesn't use. While I'm honestly fine with that behavior, it will break other stages from people who aren't around to correct their stage currently. 

Attached is a stage that will work on mugen 1.0/1,1 but look incorrect on .98.2
[stages.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/8199237/stages.zip)

**Comment by K4thos** [comment]
problem with dummy parameters affecting type = normal bg is fixed in above commit. Animated parallax taking into account actionno paramater (skipped in previous versions) is intended (mugen 1.1 feature). Ticket can be closed.
