### ISSUE TITLE
Logo sound still playing after I skip it.

### ISSUE THREAD

**Issue by UrsoManso** [Windblade-GR01/Ikemen-GO#455]
https://user-images.githubusercontent.com/77592586/157295001-ca74560e-dea4-42e0-8aee-c1ef2f62e3aa.mp4

This is the normal behavior from 98.1

https://user-images.githubusercontent.com/77592586/157295109-7153aeee-0f30-4877-af39-4a3ea72ae0ba.mp4

This is 98.2, the sound keeps playing when I skip logo screen.

**Comment by K4thos** [comment]
can't reproduce

**Comment by UrsoManso** [comment]
[logo-intro.zip](https://github.com/Windblade-GR01/Ikemen-GO/files/8214784/logo-intro.zip)

Here's my stuff, I was able to reproduce it with default build. Logo.def = logo, start.def = intro

**Comment by K4thos** [comment]
fixed, thanks
