### ISSUE TITLE
Package OpenAL form github.com/timshannon/go-openal gives a warning

### ISSUE THREAD

**Issue by pftmclub** [Windblade-GR01/Ikemen-GO#49]
Whenever i run get.cmd from build folder, it's keep saying error like this:
"c:\Go\bin>go get -u github.com/timshannon/go-openal/openal
# github.com/timshannon/go-openal/openal
go\src\github.com\timshannon\go-openal\openal\alcCore.go:29:16: warning: 'alcGet
String' redeclared without dllimport attribute: previous dllimport ignored [-Wat
tributes]
 const ALCchar *alcGetString( ALCdevice *device, ALCenum param );
                ^~~~~~~~~~~~
"

Please help, i try to run build.bat and the Ikemen-Go.exe keep closing will this result:
"open script/main.lua: The system cannot find the path specified.".

It's kind hard for this issue !

**Comment by Windblade-GR01** [comment]
That's just a warning.
It still compiles correctly.

You need the ``Script`` and ``Data`` folders from this repo extracted besides the exe.
And as I said in the build instructions you need the files from this repo:
https://github.com/Windblade-GR01/Ikemen_GO-Elecbyte-Screenpack
The folder structure should en looking like this:
![image](https://user-images.githubusercontent.com/11762096/65394843-1de63f00-dd58-11e9-8c53-6c54c96c8bbb.png)
OpenAL32.dll is optional.

Also you can find automated builds at:
https://ci.appveyor.com/project/Windblade-GR01/ikemen-go/build/artifacts
It comes packaged with everything, ready to run.

**Comment by pftmclub** [comment]
> That's just a warning.
> It still compiles correctly.
> 
> You need the `Script` and `Data` folders from this repo extracted besides the exe.
> And as I said in the build instructions you need the files from this repo:
> https://github.com/Windblade-GR01/Ikemen_GO-Elecbyte-Screenpack
> The folder structure should en looking like this:
> ![image](https://user-images.githubusercontent.com/11762096/65394843-1de63f00-dd58-11e9-8c53-6c54c96c8bbb.png)
> OpenAL32.dll is optional.
> 
> Also you can find automated builds at:
> https://ci.appveyor.com/project/Windblade-GR01/ikemen-go/build/artifacts
> It comes packaged with everything, ready to run.

Thank , i did it!
I want to ask, let's say i have a ikemen build of Card Saga Wars games. How do i convert this game to your "IKEMEN GO" build?

p/s: if you can, please check my build to see did i do something wrong: https://files.catbox.moe/shirie.zip

**Comment by pftmclub** [comment]
> I see that you still have the SRC and GO folders, these are not needed to run the engine.
> They are only needed for compilation.
> 
> Also I updated with another build with some edge cases to ignore some errors that some winmugen games generate because the lack of parameters. (Incomplete information, etc)
> So you have to update before doing this.
> 
> About card saga wars you are talking about the Online version circulating internet?
> OK here is a step by step.
> 
> * Extract the card saga wars folder.
> * Delete everything keeping only these files:
>   ![image](https://user-images.githubusercontent.com/11762096/65515656-3d3eb280-dea5-11e9-9b62-aae41ac07dc5.png)
>   `Credits.txt` and `MOVELISTS.png` are optional.
> * From your build get `Ikemen_GO.exe` and the `script` folder and paste it in the main Card Wars folder.
> * Also get Inside the data folder: `common.air`, `common.cmd` and `tournament.sff`
>   Copy and Paste these inside the Card Wars folder
> * Open the `select.def` file and replace:
>   `Training, exclude=1, order=<Insert very very big number here>`
>   With:
>   `Training, exclude=1, order=0`
> * Profit `(^▽^)`
> 
> **EDIT:**
> To make the menu Icon display correctly delete these lines (Near line 236) in `system.def`
> 
> ```ini
> p1.cursor.active.spr=
> p2.cursor.active.spr=
> p1.teammenu.bg.spr=
> p2.teammenu.bg.spr=
> ```

Thanks. I did the every step you said. and this error show in ikemen.txt:
"
.\script\motif.lua:1412: attempt to index a non-table object(nil)
stack traceback:
	.\script\motif.lua:1412: in function <.\script\motif.lua:0>
	[G]: in function 'require'
	script/main.lua:944: in main chunk
	[G]: ?
"
Do i have to update new version for this?
