### ISSUE TITLE
Audio doesn't pan like mugen

### ISSUE THREAD

**Issue by Amidweiz** [Windblade-GR01/Ikemen-GO#57]
One thing I've noticed with Ikemen GO Plus (and regular Ikemen for the matter) is that the audio doesn't pan in stereo when the characters are at different ends of the screen.

Mugen: https://streamable.com/jt4tm
Ikemen GO Plus: https://streamable.com/hf2bj

**Comment by K4thos** [comment]
done: https://github.com/K4thos/Ikemen_GO/commit/b6ff4c550e12c7c478e65ec1ff08c6fbcf47bc5e
