### ISSUE TITLE
Very slow startup

### ISSUE THREAD

**Issue by FainTMako** [Windblade-GR01/Ikemen-GO#69]
Hello, ever since I started compiling Ikemen_GO from any source I run into a weird problem. Upon reboot starting Ikemen_GO is really fast the first 2-3 times starting up. After that for some weird reason each time I start Ikemen_GO it takes nearly 30 seconds to a minute for the game client to start. After it is started it runs totally fine as expected. Full framerate etc.

Do you have any tips on how to alleviate this? I am newer to go so my understanding of this project isnt full. Im just working with what pieces I can understand / what pieces I think I need. I have been unable to get a debugger going on this but I would suspect it may be useful into figruing out why this is taking so long.

PS. It just so happens that I had this problem on my dev pc, After moving to a brand new pc with brand new windows 10 install I can verify that I am having this same exact problem on a new machine. Is anyone else having the same issue?

**Comment by Windblade-GR01** [comment]
That's interesting.
I'll hook up a profiler and see whats the problem.

**Comment by FainTMako** [comment]
Okay, I was getting very desperate and I starting logging what I could. I found out that glfw.init() was the culprit. I did some research and its apparently a glfw bug. Now I tried everything I could including building and using the latest glfw and nothing worked.

Insanely enough the solution was simply to unplug my usb keyboard and plug it  back in.....
I cannot explain why this works but its quite frustrating lmao.

Here is a link to the stackoverflow that gave me the idea. This is also why the problem persisted between my 2 different pcs when I changed over...

https://stackoverflow.com/a/52249864

**Comment by Windblade-GR01** [comment]
I'll update GLFW with Ikemen GO in hopes that it's fixed.
Other than that it seems that we can no nothing about it.

Dependencies bug are the worst for that reason.

**Comment by SeanMuggin** [comment]
Okay... I thought the keyboard fix was BS but after another 30 mins or so of digging I decided to try it and it friggin worked.... POG

**Comment by Lunakato258** [comment]
I have 2 options, 1 install the driver, 2 change the resolution to 720p instead of 1080p.
